LINUX apply AMD OC with timeout
it can hang especially on boot

diff --git a/hive/sbin/amd-oc-safe b/hive/sbin/amd-oc-safe
--- a/hive/sbin/amd-oc-safe
+++ b/hive/sbin/amd-oc-safe
@@ -25,7 +25,14 @@ if [[ -e $LOCK_FILE ]]; then
 fi
 
 echo $$ > $LOCK_FILE
-amd-oc 2>&1 | tee /var/log/amd-oc.log
+
+timeout -s9 90 amd-oc 2>&1 | tee /var/log/amd-oc.log
+
+if [[ $? -ge 124 ]]; then
+	echo -e "${RED}ERROR: AMD OC failed ${NOCOLOR}"
+	cat /var/log/amd-oc.log | message error "AMD OC failed" payload > /dev/nul
+fi
+
 rm $LOCK_FILE
 
 
