LINUX UPDATE gpu-detect * report name for unsupported by driver Nvidia gpu

diff --git a/hive/sbin/gpu-detect b/hive/sbin/gpu-detect
--- a/hive/sbin/gpu-detect
+++ b/hive/sbin/gpu-detect
@@ -133,28 +133,26 @@ if [[ "$1" == "list" || "$1" == "listjson" ]]; then
 				exitcode=$?
 				# suppress permission error at early boot
 				#{ echo "$NVIDIA_DATA" > $NVIDIASMI_FILE_V2; } 2>/dev/null
-				if [[ $exitcode -ne 0 ]]; then
+				# check for status errors here and send all in one msg
+				msg=""
+				while IFS=";" read status statusmsg gpubusid gpuname others; do
+					[[ $status -eq 0 ]] && continue
+					# NVML_ERROR_INSUFFICIENT_POWER = 8
+					msg+="GPU ${gpubusid#00000000:} $gpuname - $statusmsg ($status)"$'\n'
+				done < <( echo "$NVIDIA_DATA" | grep -v "^0;" )
+
+				if [[ ! -z "$msg" ]]; then
+					echo "$msg" >&2
+					echo "$msg" | message error "Nvidia GPU error" payload > /dev/null
+				elif [[ $exitcode -ne 0 ]]; then
 					echo "nvtool error ($exitcode)" >&2
 					echo "$NVIDIA_DATA" | message error "nvtool error ($exitcode)" payload > /dev/null
-				else
-					# check for status errors here and send all in one msg
-					msg=""
-					while IFS=";" read status statusmsg gpubusid gpuname others; do
-						[[ $status -eq 0 ]] && continue
-						# NVML_ERROR_INSUFFICIENT_POWER = 8
-						msg+="GPU ${gpubusid#00000000:} $gpuname - $statusmsg ($status)"$'\n'
-					done < <( echo "$NVIDIA_DATA" | grep -v "^0;" )
-
-					if [[ ! -z "$msg" ]]; then
-						echo "$msg" >&2
-						echo "$msg" | message error "Nvidia GPU error" payload > /dev/null
-					fi
 				fi
 			fi
 
 			IFS=";" read status statusmsg gpubusid gpuname vbios mem usedmem freemem plim_def plim_min plim_max fan_cnt memvendor others < <( echo "$NVIDIA_DATA" | grep -i "00000000:$busid" )
 			if [[ ! -z "$gpuname" ]]; then
-				name="$gpuname"
+				[[ ! "$gpuname" =~ "Graphics Device" ]] && name="$gpuname"
 				[[ ! -z "$mem" ]] && mem="$mem MB"
 				[[ ! -z "$plim_min" ]] && plim_min="${plim_min/.0/} W"
 				[[ ! -z "$plim_def" ]] && plim_def="${plim_def/.0/} W"
