LINUX FIX hive-replace - added support for Ubuntu 14 based OS
prevent infinite loop while killing processes
stop miners before image download to free memory

diff --git a/hive/sbin/hive-replace b/hive/sbin/hive-replace
--- a/hive/sbin/hive-replace
+++ b/hive/sbin/hive-replace
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-export PATH=/bin:/sbin:/usr/bin:/usr/sbin
+#export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin
 
 SCRIPT_PATH=`dirname $0`
 SCRIPT_NAME=`basename $0`
@@ -38,7 +38,7 @@ smbuser=
 smbpasswd=
 nfs=0
 thishive=0
-[[ $(uname -sr) == *hive* ]] && thishive=1
+[[ $(uname -sr) == *hive* ]] && thishive=1 && export PATH=/hive/bin:/hive/sbin:$PATH
 
 #Get root
 if [[ $(id -u) -ne 0 ]]; then
@@ -147,7 +147,7 @@ function get_image_from_list {
 	done
 
 	# allow to select only in interactive shell
-	if [[ $(tty) == *tty* || ! -z $DISPLAY ]]; then
+	if [[ $(tty) == *tty* ]]; then
 		echo -e "${RED}Run this script in interactive shell (local console in not supported) to select image. Exiting.$NOCOLOR"
 		exit 0
 	fi
@@ -197,7 +197,7 @@ function usage {
 function check_packages {
 	local programs=0
 	local need_install=
-	
+
 	dpkg -s lsof > /dev/null 2>&1
 	[[ $? -ne 0 ]] && programs=1 && need_install="lsof"
 	dpkg -s curl > /dev/null 2>&1
@@ -233,7 +233,7 @@ function get {
 
 	basename=`basename -s .zip "$url"`
 	archname=`basename "$url"`
-	
+
 	if [[ $nfs -eq 1 || $smb -eq 1 ]]; then
 		[[ ! -d $TMPDIR/share ]] && mkdir $TMPDIR/share
 		mnt_flag=1
@@ -248,7 +248,7 @@ function get {
 			[[ ! -z $smbpasswd ]] && psw="password=$smbpasswd"
 			mount -v -t cifs -o username=$smbuser,$psw,iocharset=utf8,vers=3.0 $(dirname "$url") $TMPDIR/share > /dev/null 2>&1
 			mnt_flag=$?
-		fi	
+		fi
 		[[ $mnt_flag -ne 0 ]] && echo -e "${RED}Сan't mount network shared resource.${NOCOLOR}" && return 1
 		url="$TMPDIR/share/$archname"
 	fi
@@ -265,11 +265,14 @@ function get {
 		[[ -z $mdsum ]] && echo -e "${RED}Сan't get md5sum from $md5_url to check MD5 checksum. Use -f to ignore this.${NOCOLOR}" && return 1
 	fi
 
+	# stop miner here to free some memory and prevent rig from rebooting on errors
+	[[ $thishive -eq 1 ]] && miner stop 2>/dev/null
+
 	#Copy|download hive image to tmmfs
 	echo -e "\n${CYAN}> Downloading image file${NOCOLOR}"
 	if [[ "$url" == *http* ||  "$url" == *ftp* ]]; then
 		echo ""
-		wget -t 0 -T $TIMEOUT --show-progress "$url"
+		wget -t 0 -T $TIMEOUT "$url"
 		[[ $? -ne 0 ]] && echo -e "${RED}Download Hive OS image failed. Check url${NOCOLOR}" && return 1
 	else
 		[[ ! -f $url ]] && echo -e "${RED}Hive OS image not found. Check path${NOCOLOR}" && return 1
@@ -289,7 +292,7 @@ function get {
 	unzip -t $TMPDIR/$archname > /dev/null
 	[[ $? -ne 0 ]] && echo -e "${RED}ZIP file is damaged${NOCOLOR}" && return 1
 
-	echo -e "${GREEN}Download|copy Hive OS image successful!${NOCOLOR}"
+	echo -e "${GREEN}Hive OS image ready!${NOCOLOR}"
 	return 0
 }
 
@@ -297,7 +300,7 @@ function get {
 # Starting actions
 function prepare {
 	#Prevent start from local console
-	[[ $(tty) == *tty* || ! -z $DISPLAY ]] && echo "This script does not work in the local console. Exiting." && exit 1
+	[[ $(tty) == *tty* ]] && echo "This script does not work in the local console. Exiting." && exit 1
 
 	mem=$(free -m | awk 'NR == 2{print$2}')
 	clear
@@ -317,12 +320,12 @@ function prepare {
 	DISK_SIZE=`cat /proc/partitions | grep -w "${DISK_NAME}" | awk '{ printf("%.f",$3/1024)}'`
 	PART_SIZE=`cat /proc/partitions | grep -w "${DISK_PART}" | awk '{ printf("%.f",$3/1024)}'`
 
-	echo -e "Current OS booted from ${GREEN}$DISK_NAME${NOCOLOR} and whole drive size is ${WHITE}$DISK_SIZE${NOCOLOR} Mb"
+	echo -e "Current OS booted from ${BPURPLE}$DISK_NAME${NOCOLOR} and whole drive size is ${WHITE}$DISK_SIZE${NOCOLOR} Mb"
 	[[ $DISK_SIZE -lt 7300 ]] && echo -e "\n${YELLOW}The minimum disk size for Hive OS is 8 Gb${NOCOLOR}" && exit
 
 	if [[ $no_confirm -ne 1 ]]; then
-		echo -e "${RED}Warning: After Hive OS installation, all your data on ${GREEN}$DISK_NAME${NOCOLOR} ${RED}will be lost!${NOCOLOR}"
-		echo -en "\nType ${GREEN}\"yes\"${NOCOLOR} if you want to install Hive OS on ${GREEN}$DISK_NAME${NOCOLOR}: "
+		echo -e "${RED}Warning: After Hive OS installation, all your data on ${BPURPLE}$DISK_NAME${NOCOLOR} ${RED}will be lost!${NOCOLOR}"
+		echo -en "\nType ${GREEN}\"yes\"${NOCOLOR} if you want to install Hive OS on ${BPURPLE}$DISK_NAME${NOCOLOR}: "
 		read answer
 		[[ $answer != "yes" ]] && echo -e "${YELLOW}\nBye, bye!${NOCOLOR}" && exit
 	fi
@@ -351,9 +354,8 @@ function prepare {
 	[[ $thishive -eq 1 && -d /hive-config/watchdog ]] && cp -R /hive-config/watchdog $TMPDIR/old-config/
 
 
-	#get hive zip
-	get
-	[[ $? -ne 0 ]] && exit
+	# get hive zip
+	get || exit
 
 	#Disable kernel message to tty
 	echo 0 > /proc/sys/kernel/printk
@@ -363,42 +365,37 @@ function prepare {
 
 	#stop services and remount RO
 	swapoff -a
-	echo -e "\n${CYAN}> Stopping services${NOCOLOR}"
-
+	
 	if [[ $thishive -eq 1 ]]; then
-		####################
-		#There must be a watchdog stop
-		##################
-
-		autoswitch stop > /dev/null 2>&1
-		miner stop > /dev/null 2>&1
-		wd stop > /dev/null 2>&1
-		autofan stop > /dev/null 2>&1
-		systemctl stop hivex > /dev/null 2>&1
-		[[ ! -z `pidof xinit` ]] && kill -9 `pidof xinit` > /dev/null 2>&1
+		nvstop
+		#autoswitch stop > /dev/null 2>&1
+		#miner stop > /dev/null 2>&1
+		#wd stop > /dev/null 2>&1
+		#autofan stop > /dev/null 2>&1
+		#systemctl stop hivex > /dev/null 2>&1
+		#[[ ! -z `pidof xinit` ]] && kill -9 `pidof xinit` > /dev/null 2>&1
+	else
+		echo -e "\n${CYAN}> Stopping services${NOCOLOR}"
 	fi
 
-	for SOCKET in \
-	`systemctl list-units -t socket | awk '{print $1}' | grep -v -e ssh | grep -v -e openvpn | grep -v -e shellinabox | grep -v -e network | grep -v -e ifup | grep -v -e user | grep -v -e hive`; \
-	do systemctl stop $SOCKET > /dev/null 2>&1 && echo "> stop $SOCKET"; done
 
-	for SERVICE in \
-	`systemctl list-units -t service | awk '{print $1}' | grep -v -e ssh | grep -v -e openvpn | grep -v -e shellinabox | grep -v -e network | grep -v -e ifup | grep -v -e user | grep -v -e hive`; \
-	do systemctl stop $SERVICE > /dev/null 2>&1 && echo "> stop $SERVICE"; done
-	
-	#skip self, telec, hssh, watchdog!
-	pid="1"
-	while [[ ! -z $pid ]]; do
-		pid=$(lsof / | grep -v ' \(mem\|txt\|rtd\|cwd\) ' | grep -v -e $SCRIPT_NAME | grep -v -e network -e telec -e hssh -e watchdog -e hl340 -e srrv2 | sed '2!d' | awk '{print $2}') #'
-		[[ -z $pid ]] && continue
-		process=$(lsof / | grep -v ' \(mem\|txt\|rtd\|cwd\) ' | grep -v -e $SCRIPT_NAME | grep -v -e network -e telec -e hssh -e watchdog -e hl340 -e srrv2 | sed '2!d' | awk '{print $1}') #'
-		echo -e "> kill $process"
-		kill $pid
+	for service in `initctl list 2>/dev/null | grep "/running" | grep -v -P "network|ssh|openvpn" | awk '{print $1}'`; do
+		initctl stop $service > /dev/null 2>&1 && echo "> stop $service";
+	done
+
+	for service in `systemctl list-units 2>/dev/null | grep -oP "\K[^\s]+\.(service|socket)" | grep -v -P "ssh|openvpn|shellinabox|network|ifup|user|hive"`; do
+		systemctl stop $service > /dev/null 2>&1 && echo "> stop $service";
+	done
+
+	for i in {1..3}; do
+		for pid in `lsof / | grep -v -P "^COMMAND|$SCRIPT_NAME| (mem|txt|rtd|cwd) |network|telec|hssh|watchdog|hl340|srrv2" | awk '{print $2}'`; do
+			cmd=`ps -p $pid -o args | tail -n 1`
+			kill -9 $pid 2>/dev/null && echo -e "> kill $pid: $cmd"
+		done
 		sleep 1
 	done
-	
 
-	#Readonly remount
+	# Readonly remount
 	for MOUNTS in `cat /proc/mounts | grep $DISK_NAME | awk '{print $2}'`; do
 		mount -n -o remount,ro $MOUNTS > /dev/null 2>&1;
 	done
@@ -420,7 +417,7 @@ function prepare {
 	cp -aR /dev $TMPDIR > /dev/null 2>&1
 	cp $myself $TMPDIR > /dev/null 2>&1
 	chmod +x $TMPDIR/$SCRIPT_NAME > /dev/null 2>&1
-	
+
 	mount --bind /proc $TMPDIR/proc
 	mount --bind /sys $TMPDIR/sys
 	mount --bind /dev $TMPDIR/dev
@@ -444,42 +441,44 @@ function prepare {
 
 # Writing to disk
 function write {
+    dd --help | grep -q "progress" && progress="status=progress" || progress=
 
 	cd /
 	[[ -z $archname || ! -f $archname ]] && echo -e "${RED}>HiveOS image not found. Exiting.${NOCOLOR}" && return 1
 
-	echo -e "\n${CYAN}> Writing Hive OS filesystem to $root_dev${NOCOLOR}"
+	echo -e "\n${CYAN}> Writing Hive OS filesystem to ${BPURPLE}$root_dev${NOCOLOR}"
 	echo -e "Please wait, this can take long"
 	echo -e "To prevent damage to your disk device\ndo not turn off your computer until the end of the process.\n"
 
-	unzip -p $archname | dd of=/dev/$root_dev status=progress bs=20M
+	unzip -p $archname | dd of=/dev/$root_dev bs=1M $progress
 	[[ $? -ne 0 ]] && echo -e "Write image failed. Exiting." && return 1
-	
-	partprobe > /dev/null 2>&1
 
 	#Rewrite config partition
-	dd if=/dev/${root_dev}1 of=new_conf.img status=progress
+	if [[ $thishive -eq 1 ]]; then
+		partprobe > /dev/null 2>&1
 
-	LOOPDEV=$(losetup --find --show new_conf.img)
-	partprobe ${LOOPDEV}
-	
-	mkdir hive-config
-	mount ${LOOPDEV} hive-config
-	cp -R old-config/* hive-config
-	sync
+		dd if=/dev/${root_dev}1 of=new_conf.img bs=1M $progress
 
-	dd if=/new_conf.img of=/dev/${root_dev}1 status=progress
-	
-	#Fix GPT table if needed
-	partprobe > /dev/null 2>&1
-	sgdisk -e /dev/$root_dev > /dev/null 2>&1
-	sgdisk -C /dev/$root_dev > /dev/null 2>&1
-			
-	#Reboot
+		LOOPDEV=$(losetup --find --show new_conf.img)
+		partprobe ${LOOPDEV}
+
+		mkdir hive-config
+		mount ${LOOPDEV} hive-config
+		cp -R old-config/* hive-config
+		sync
+
+		dd if=/new_conf.img of=/dev/${root_dev}1 bs=1M $progress
+
+		#Fix GPT table if needed
+		partprobe > /dev/null 2>&1
+		sgdisk -e /dev/$root_dev > /dev/null 2>&1
+		sgdisk -C /dev/$root_dev > /dev/null 2>&1
+	fi
+
 	sync
 
 	echo -e
-	echo -e "${GREEN}Image writing to ${PURPLE}$root_dev${GREEN} is successfull!${NOCOLOR}"
+	echo -e "${GREEN}Image writing to ${BPURPLE}$root_dev${GREEN} is successfull!${NOCOLOR}"
 	echo -e
 	echo -e "Your rig is configured and ready to work under Hive OS."
 	echo -e "After reboot it should appear on the web."
@@ -489,9 +488,9 @@ function write {
 
 	sleep 15
 
+	#Reboot
 	echo 1 > /proc/sys/kernel/sysrq
 	echo b > /proc/sysrq-trigger
-	
 }
 
 
@@ -539,7 +538,7 @@ for param in "$@"; do
 			get_image_from_url "$param" "this" || exit
 		;;
 		*hive*zip)
-			url=$( url_decode "$1" )
+			url=$( url_decode "$param" )
 		;;
 		-l|--list)
 			check_packages
