LINUX ADD hive-replace * label-replace

diff --git a/hive/sbin/hive-replace b/hive/sbin/hive-replace
--- a/hive/sbin/hive-replace
+++ b/hive/sbin/hive-replace
@@ -10,30 +10,35 @@ if [ $0 = "sh" ] || [ $0 = "bash" ]; then
 	exit 1
 fi
 
-
 DIR=`pwd`
 SCRIPT_PATH=$( cd $(dirname ${BASH_SOURCE[0]}) && pwd )
 SCRIPT_NAME=`basename "$0"`
 
-# main url to images repo
-HIVE_URL=https://download.hiveos.farm
 # repo list
-HIVEREPO_LIST=/etc/apt/sources.list.d/hiverepo.list
+REPO_LIST=/etc/apt/sources.list.d/hiverepo.list
+
+[[ -e /etc/brand.conf ]] && source /etc/brand.conf
+if [[ -z $DOWNLOAD_URL ]]; then
+	# main url to images repo
+	DOWNLOAD_URL=https://download.hiveos.farm
+	# direct urls to images
+	STABLE_URL=$DOWNLOAD_URL/latest/
+	VEGA_URL=$DOWNLOAD_URL/vega/
+	BETA_URL=$DOWNLOAD_URL/beta/
+	# images archive
+	IMAGES_URL=$DOWNLOAD_URL/history/
+else
+	IMAGES_URL=$DOWNLOAD_URL
+fi
+
+[[ -z $OS_BRAND ]] && OS_BRAND="hiveos"
+[[ -z $BRAND ]] && BRAND="Hive"
+[[ -z $HIVE_HOST_URL ]] && HIVE_HOST_URL="https://api.hiveos.farm"
 
 # image file mask
-HIVEOS_REGEX="hiveos-[^\"]+\.(zip|xz)"
-
-# direct urls to images
-STABLE_URL=$HIVE_URL/latest/
-VEGA_URL=$HIVE_URL/vega/
-BETA_URL=$HIVE_URL/beta/
-URL_MASK="^(http|ftp|https)://.*/${HIVEOS_REGEX}$"
-
-# images archive
-ARCHIVE_URL=$HIVE_URL/history/
-
-#ARCHIVE_REGEX="\"\Khiveos-[^\"]+.zip(?=\")"
-ARCHIVE_REGEX="(\"|^)\K${HIVEOS_REGEX}(?=(\"|$))"
+OS_REGEX="$OS_BRAND-[^\"]+\.(zip|xz)"
+URL_MASK="^(http|ftp|https)://.*/${OS_REGEX}$"
+ARCHIVE_REGEX="(\"|^)\K${OS_REGEX}(?=(\"|$))"
 
 # download timeout
 TIMEOUT=20
@@ -74,13 +79,13 @@ LGRAY=$'\033[0;37m'
 WHITE=$'\033[1;37m'
 GRAY=$'\033[2;37m'
 
-[[ $(uname -sr) == *hive* ]] && thishive=1
+[[ $(uname -sr) == *$OS_BRAND* ]] && thishive=1
 
 
 function exit_handler {
 	echo -e "\npress any key to close session"
-	if [[ -t 0 ]]; then 
-		read -n 1 
+	if [[ -t 0 ]]; then
+		read -n 1
 	else
 		read -n 1 -t 600
 	fi
@@ -111,11 +116,11 @@ function get_image_from_list {
 	local select="$1"
 	local repo="$2"
 
-	[[ -z "$repo" ]] && URL=$ARCHIVE_URL || URL="$repo"
+	[[ -z "$repo" ]] && URL=$IMAGES_URL || URL="$repo"
 	# trailing slash needed
 	[[ ! "$URL" =~ /$ ]] && URL+="/"
 
-	echo -e "${CYAN}> Loading Hive OS images list from ${BCYAN}${URL}${NOCOLOR}"
+	echo -e "${CYAN}> Loading $BRAND OS images list from ${BCYAN}${URL}${NOCOLOR}"
 
 	local urls=()
 	local arr=()
@@ -123,9 +128,9 @@ function get_image_from_list {
 
 	# skip for custom repo
 	if [[ -z "$repo" ]]; then
-		get_image_from_url $STABLE_URL "Stable" && urls+=("$url") && IMAGE["$url"]="Latest Stable"
-		get_image_from_url $BETA_URL "Beta" && urls+=("$url") && IMAGE["$url"]="Latest Beta"
-		get_image_from_url $VEGA_URL "Vega" && urls+=("$url") && IMAGE["$url"]="Latest Vega"
+		[[ ! -z $STABLE_URL ]] && get_image_from_url $STABLE_URL "Stable" && urls+=("$url") && IMAGE["$url"]="Latest Stable"
+		[[ ! -z $BETA_URL ]] && get_image_from_url $BETA_URL "Beta" && urls+=("$url") && IMAGE["$url"]="Latest Beta"
+		[[ ! -z $VEGA_URL ]] && get_image_from_url $VEGA_URL "Vega" && urls+=("$url") && IMAGE["$url"]="Latest Vega"
 		url=
 	fi
 
@@ -133,7 +138,7 @@ function get_image_from_list {
 	if [[ -e "$URL" ]]; then
 		# local path
 		list=`ls -l "$URL" 2>/dev/null` &&
-			readarray -t arr < <( echo "$list" | grep -oP "$HIVEOS_REGEX" | sort -n -t "@" -k1 )
+			readarray -t arr < <( echo "$list" | grep -oP "$OS_REGEX" | sort -n -t "@" -k1 )
 	else
 		# works for ftp also
 		list=`curl -fskL --list --connect-timeout $TIMEOUT --retry 2 "$URL" 2>/dev/null` &&
@@ -159,7 +164,7 @@ function get_image_from_list {
 	# try to get from repo URL if specified
 	[[ ! -z "$repo" ]] && versions=`curl -fsLk --connect-timeout $TIMEOUT --retry 2 "${URL}VERSIONS.txt" 2>/dev/null`
 	# try to get from Hive server
-	[[ -z $versions ]] && versions=`curl -fsLk --connect-timeout $TIMEOUT --retry 2 "${HIVE_URL}/VERSIONS.txt" 2>/dev/null`
+	[[ -z $versions ]] && versions=`curl -fsLk --connect-timeout $TIMEOUT --retry 2 "${DOWNLOAD_URL}/VERSIONS.txt" 2>/dev/null`
 	[[ -z $versions ]] && echo -e "${RED}> Unable to load image descriptions${NOCOLOR}"
 	local SEP=" · "
 	local index=0
@@ -191,7 +196,7 @@ function get_image_from_list {
 			amd=`echo "$info" | grep -m1 -ioP "^amd[^\s]* \K.*"` && ver+="${SEP}${RED}A${NOCOLOR} $amd"
 			#boot=`echo "$info" | grep -m1 "^Dual"` && ver+="${SEP}$boot"
 			# get last line for desc
-			desc=`echo "$info" | tail -n 1 | grep -ivP "^(amd|nvidia|Linux|md5|hiveos)"` && ver+="${SEP} $desc"
+			desc=`echo "$info" | tail -n 1 | grep -ivP "^(amd|nvidia|Linux|md5|$OS_BRAND)"` && ver+="${SEP} $desc"
 		fi
 		((index++))
 		printf "%b%2s) %b\n" $WHITE $index "${NOCOLOR}$ver"
@@ -249,7 +254,7 @@ function check_packages {
 # Gets/downloads image
 function get_image {
 	cd $TMPDIR
-	rm $TMPDIR/*hive* > /dev/null 2>&1
+	rm $TMPDIR/*$OS_BRAND* > /dev/null 2>&1
 
 	archname=`basename "$url"`
 
@@ -311,11 +316,11 @@ function get_image {
 	if [[ "$url" == http* ||  "$url" == ftp* ]]; then
 		echo ""
 		wget -t 0 -T $TIMEOUT --no-check-certificate "$url"
-		[[ $? -ne 0 ]] && echo -e "${RED}Download Hive OS image failed. Check url${NOCOLOR}" && return 1
+		[[ $? -ne 0 ]] && echo -e "${RED}Download $BRAND OS image failed. Check url${NOCOLOR}" && return 1
 	else
-		[[ ! -f $url ]] && echo -e "${RED}Hive OS image not found. Check path${NOCOLOR}" && return 1
+		[[ ! -f $url ]] && echo -e "${RED}$BRAND OS image not found. Check path${NOCOLOR}" && return 1
 		cp -v $url $TMPDIR
-		[[ $? -ne 0 ]] && echo -e "${RED}Copy Hive OS image failed${NOCOLOR}" && return 1
+		[[ $? -ne 0 ]] && echo -e "${RED}Copy $BRAND OS image failed${NOCOLOR}" && return 1
 	fi
 
 	# check md5
@@ -334,7 +339,7 @@ function get_image {
 	fi
 	[[ $? -ne 0 ]] && echo -e "${RED}Archive is damaged${NOCOLOR}" && return 1
 
-	echo -e "${GREEN}Hive OS image ready!${NOCOLOR}"
+	echo -e "${GREEN}$BRAND OS image ready!${NOCOLOR}"
 	return 0
 }
 
@@ -361,7 +366,7 @@ function prepare {
 	#clear
 	echo -e "\n"
 	echo -e "${CYAN}***********************************${NOCOLOR}"
-	echo -e "${YELLOW}    Hive OS Image Installation${NOCOLOR}"
+	echo -e "${YELLOW}    $BRAND OS Image Installation${NOCOLOR}"
 	echo -e "${CYAN}***********************************${NOCOLOR}"
 	echo
 	echo -e "$WHITE$url${NOCOLOR}"
@@ -386,11 +391,11 @@ function prepare {
 	PART_SIZE=`cat /proc/partitions | grep -w "${DISK_PART}" | awk '{ printf("%.f",$3/1024)}'`
 
 	echo -e "Current OS booted from ${BPURPLE}$DISK_NAME${NOCOLOR} and whole drive size is ${WHITE}$DISK_SIZE${NOCOLOR} Mb"
-	[[ $DISK_SIZE -lt 7300 ]] && echo -e "\n${YELLOW}The minimum disk size for Hive OS is 8 Gb${NOCOLOR}" && exit
+	[[ $DISK_SIZE -lt 7300 ]] && echo -e "\n${YELLOW}The minimum disk size for $BRAND OS is 8 Gb${NOCOLOR}" && exit
 
 	if [[ $no_confirm -ne 1 ]]; then
-		echo -e "${RED}Warning: After Hive OS installation, all your data on ${BPURPLE}$DISK_NAME${NOCOLOR} ${RED}will be lost!${NOCOLOR}"
-		echo -en "\nType ${GREEN}\"yes\"${NOCOLOR} if you want to install Hive OS on ${BPURPLE}$DISK_NAME${NOCOLOR}: "
+		echo -e "${RED}Warning: After $BRAND OS installation, all your data on ${BPURPLE}$DISK_NAME${NOCOLOR} ${RED}will be lost!${NOCOLOR}"
+		echo -en "\nType ${GREEN}\"yes\"${NOCOLOR} if you want to install $BRAND OS on ${BPURPLE}$DISK_NAME${NOCOLOR}: "
 		read -t 90 answer
 		[[ $answer != "yes" ]] && echo -e "${YELLOW}\nBye, bye!${NOCOLOR}" && exit 0
 	fi
@@ -410,7 +415,7 @@ function prepare {
 	if [[ $thishive -eq 1 && -f /hive-config/rig.conf ]]; then
 		cp /hive-config/rig.conf ${TMPDIR}/old-config/
 	elif [[ ! -z $farm ]]; then
-		echo -e "HIVE_HOST_URL=\"https://api.hiveos.farm\"" > ${TMPDIR}/old-config/rig.conf
+		echo -e "HIVE_HOST_URL=\"$HIVE_HOST_URL\"" > ${TMPDIR}/old-config/rig.conf
 		echo -e "FARM_HASH=$farm\n" >> ${TMPDIR}/old-config/rig.conf
 	fi
 	[[ $thishive -eq 1 && -d /hive-config/network ]] && cp -R /hive-config/network $TMPDIR/old-config/
@@ -420,7 +425,7 @@ function prepare {
 	# stop miner and some services to reduce RAM usage and prevent reboot
 
 	if [[ $thishive -eq 1 ]]; then
-		echo -e "\n${CYAN}> Stopping Hive OS services${NOCOLOR}"
+		echo -e "\n${CYAN}> Stopping $BRAND OS services${NOCOLOR}"
 		autoswitch stop > /dev/null 2>&1
 		miner stop > /dev/null 2>&1
 		autofan stop > /dev/null 2>&1
@@ -521,9 +526,9 @@ function prepare {
 # Writing to disk
 function write {
 	cd /
-	[[ -z $archname || ! -f $archname ]] && echo -e "${RED}>HiveOS image not found, exiting${NOCOLOR}" && return 1
+	[[ -z $archname || ! -f $archname ]] && echo -e "${RED}> $BRAND OS image not found, exiting${NOCOLOR}" && return 1
 
-	echo -e "\n${CYAN}> Writing Hive OS filesystem to ${BPURPLE}$root_dev${NOCOLOR}"
+	echo -e "\n${CYAN}> Writing $BRAND OS filesystem to ${BPURPLE}$root_dev${NOCOLOR}"
 	echo -e "Please wait, this can take long"
 	echo -e "To prevent damage to your disk device\ndo not turn off your computer until the end of the process.\n"
 
@@ -558,7 +563,7 @@ function write {
 	    # we do not need it any more
 	    rm $archname > /dev/null 2>&1
 
-		echo -e "\n${CYAN}> Writing Hive OS config to ${BPURPLE}$root_dev${NOCOLOR}"
+		echo -e "\n${CYAN}> Writing $BRAND OS config to ${BPURPLE}$root_dev${NOCOLOR}"
 
 		dd if=/dev/${conf_part} of=new_conf.img bs=1M
 
@@ -582,7 +587,7 @@ function write {
 	echo -e
 	echo -e "${GREEN}Image writing to ${BPURPLE}$root_dev${GREEN} is successfull!${NOCOLOR}"
 	echo -e
-	echo -e "Your rig is configured and ready to work under Hive OS."
+	echo -e "Your rig is configured and ready to work under $BRAND OS."
 
 	if [[ $configured -eq 1 ]]; then
 		[[ -f old-config/rig.conf ]] && source old-config/rig.conf
@@ -603,7 +608,7 @@ function start {
 	[[ -f "/replace.conf" ]] && source "/replace.conf"
 
 	if [[ $wr -ne 1 ]]; then
-		[[ -z "$url" ]] && echo -e "${YELLOW}Filesystem path or URL to Hive OS image is required.${NOCOLOR}\n" && usage
+		[[ -z "$url" ]] && echo -e "${YELLOW}Filesystem path or URL to $BRAND OS image is required.${NOCOLOR}\n" && usage
 		prepare
 	else
 		write
@@ -618,21 +623,23 @@ function start {
 
 function usage {
 	local code=$1
-	echo -e "${CYAN}Usage: hive-replace [option] <Path or URL to ZIP/XZ file with Hive OS image>${NOCOLOR}"
+	echo -e "${CYAN}Usage: hive-replace [option] <Path or URL to ZIP/XZ file with $BRAND OS image>${NOCOLOR}"
 	echo -e
 	echo -e "Options:"
-	echo -e "${GREEN}  -l|--list|--list=NUM    ${NOCOLOR}List images from Hive server and select for install (or download)"
-	echo -e "${GREEN}  -s|--stable             ${NOCOLOR}Download and install latest ${BCYAN}Stable${NOCOLOR} image from Hive server"
-	echo -e "${GREEN}  --vega                  ${NOCOLOR}Download and install latest ${CYAN}Vega${NOCOLOR} image from Hive server"
-	echo -e "${GREEN}  --beta                  ${NOCOLOR}Download and install latest ${CYAN}Beta${NOCOLOR} image from Hive server"
+	echo -e "${GREEN}  -l|--list|--list=NUM    ${NOCOLOR}List images from $BRAND server and select for install (or download)"
+	echo -e "${GREEN}  -s|--stable             ${NOCOLOR}Download and install latest ${BCYAN}Stable${NOCOLOR} image from $BRAND server"
+	[[ ! -z $VEGA_URL ]] &&
+		echo -e "${GREEN}  --vega                  ${NOCOLOR}Download and install latest ${CYAN}Vega${NOCOLOR} image from $BRAND server"
+	[[ ! -z $BETA_URL ]] &&
+		echo -e "${GREEN}  --beta                  ${NOCOLOR}Download and install latest ${CYAN}Beta${NOCOLOR} image from $BRAND server"
 	echo -e "${GREEN}  --repo[=URL]            ${NOCOLOR}List images from custom repository (specified by URL) and select for install (HTTP(S)/FTP)"
 	echo -e "${GREEN}  -y|--yes                ${NOCOLOR}Do not ask for confirmation, answer yes to all questions"
 	echo -e "${GREEN}  --force                 ${NOCOLOR}Force replace if RAM is less than 3GB. Use on your own risk"
 	echo -e "${GREEN}  --safe                  ${NOCOLOR}Run replace in safer way so running session can be resumed (run hive-replace or screen -r replace)"
 	echo -e "${GREEN}  --download=PATH         ${NOCOLOR}Download image to PATH (without replace). Can be used with other options (--stable)"
 	echo -e "${GREEN}  --hash=FARM_HASH        ${NOCOLOR}FARM_HASH from Web-interface. Optional for already configured rig"
-	echo -e "${GREEN}  --nfs                   ${NOCOLOR}To use NFS Shared resource. e.g.: ${GREEN}IP_NFS_server:/shared_dir/hive_image${NOCOLOR}"
-	echo -e "${GREEN}  --smb                   ${NOCOLOR}To use Windows Shared resource. e.g.: ${GREEN}//IP_Windows_comp/shared_folder/hive_image${NOCOLOR}"
+	echo -e "${GREEN}  --nfs                   ${NOCOLOR}To use NFS Shared resource. e.g.: ${GREEN}IP_NFS_server:/shared_dir/image_file${NOCOLOR}"
+	echo -e "${GREEN}  --smb                   ${NOCOLOR}To use Windows Shared resource. e.g.: ${GREEN}//IP_Windows_comp/shared_folder/image_file${NOCOLOR}"
 	echo -e "${GREEN}  --smbuser=Windows user  ${NOCOLOR}UserName for Windows Shared resource. Do not set this option for guest/anonymous access"
 	echo -e "${GREEN}  --smbpass=Windows pass  ${NOCOLOR}Password for Windows Shared resource. Do not set this option for guest/anonymous access"
 	echo -e "${GREEN}  -h|--help               ${NOCOLOR}Show this message"
@@ -641,10 +648,10 @@ function usage {
 	echo -e "Examples:"
 	echo -e "${GREEN}  hive-replace -y --stable${NOCOLOR}"
 	echo -e "${GREEN}  hive-replace -y --list${NOCOLOR}"
-	echo -e "${GREEN}  hive-replace -y --list=3${NOCOLOR}"
-	echo -e "${GREEN}  hive-replace -y --hash=46e9602837d0bda99f0 http://mylocalserver/hiveos-0.6-01@181121.zip${NOCOLOR}"
-	echo -e "${GREEN}  hive-replace -y --hash=46e9602837d0bda99f0 --nfs 192.168.10.100:/home/john/hive/hiveos-0.6-01@181121.zip${NOCOLOR}"
-	echo -e "${GREEN}  hive-replace -y --smb --smbuser=winuser --smbpass=secret //192.168.0.1/shared_folder/hiveos-0.6-01@181121.zip${NOCOLOR}"
+	echo -e "${GREEN}  hive-replace -y --list=3 --repo=http://mylocalserver/images/${NOCOLOR}"
+	echo -e "${GREEN}  hive-replace -y --hash=46e9602837d0bda99f0 http://mylocalserver/$OS_BRAND-0.6.zip${NOCOLOR}"
+	echo -e "${GREEN}  hive-replace -y --hash=46e9602837d0bda99f0 --nfs 192.168.10.100:/home/john/hive/$OS_BRAND-0.6.zip${NOCOLOR}"
+	echo -e "${GREEN}  hive-replace -y --smb --smbuser=winuser --smbpass=secret //192.168.0.1/shared_folder/$OS_BRAND-0.6.xz${NOCOLOR}"
 	exit 0
 }
 
@@ -714,11 +721,11 @@ for param in "$@"; do
 		--hash=*)
 			farm="${param#*=}"
 		;;
-		https://*hive*|http://*hive*|ftp://*hive*)
+		https://*$OS_BRAND*|http://*$OS_BRAND*|ftp://*$OS_BRAND*)
 			check_packages
 			get_image_from_url "$param" "this" || exit
 		;;
-		*hive*.xz|*hive*.zip)
+		*$OS_BRAND*.xz|*$OS_BRAND*.zip)
 			[[ -f "$DIR/$param" ]] && param="$DIR/$param"
 			url=$( url_decode "$param" )
 		;;
@@ -730,9 +737,9 @@ for param in "$@"; do
 			listparams[0]="${param#*=}"
 		;;
 		--repo)
-			[[ ! -f $HIVEREPO_LIST ]] && echo -e "${RED}> No default repository, exiting${NOCOLOR}" && exit 1
-			repo=`grep -m1 -oP "deb\s*\K[^\s]+/repo/" $HIVEREPO_LIST`
-			[[ -z "$repo" || "$repo" =~ "${HIVE_URL##*/}" ]] && echo -e "${RED}> No custom repository, exiting${NOCOLOR}" && exit 1
+			[[ ! -f $REPO_LIST ]] && echo -e "${RED}> No default repository, exiting${NOCOLOR}" && exit 1
+			repo=`grep -m1 -oP "deb\s*\K[^\s]+/repo/" $REPO_LIST`
+			[[ -z "$repo" || "$repo" =~ "${DOWNLOAD_URL##*/}" ]] && echo -e "${RED}> No custom repository, exiting${NOCOLOR}" && exit 1
 			listparams[1]="$repo"
 		;;
 		--repo=*)
@@ -740,14 +747,20 @@ for param in "$@"; do
 			listparams[1]="${param#*=}"
 		;;
 		-s|--stable)
-			check_packages
-			get_image_from_url $STABLE_URL "Stable" || exit
+			if [[ -z $STABLE_URL ]]; then
+				listparams[0]="1"
+			else
+				check_packages
+				get_image_from_url $STABLE_URL "Stable" || exit
+			fi
 		;;
 		--beta)
+			[[ -z $BETA_URL ]] && exit
 			check_packages
 			get_image_from_url $BETA_URL "Beta" || exit
 		;;
 		--vega)
+			[[ -z $VEGA_URL ]] && exit
 			check_packages
 			get_image_from_url $VEGA_URL "Vega" || exit
 		;;
@@ -783,7 +796,7 @@ if [[ ! -z "$download_path" ]]; then
 	get_image
 	exitcode=$?
 	if [[ $exitcode -eq 0 ]]; then
-		mv -f $TMPDIR/*hive* $download_path
+		mv -f $TMPDIR/*$OS_BRAND* $download_path
 		#get_image_from_list -1 "$download_path"
 	fi
 	cd $DIR
