control files, mkdeb

diff --git a/hive/sbin/mkdeb b/hive/sbin/mkdeb
--- a/hive/sbin/mkdeb
+++ b/hive/sbin/mkdeb
@@ -1,19 +1,33 @@
 #!/usr/bin/env bash
 
 cd `dirname $0`/../..
-
-#[ -t 1 ] &&
 . hive/bin/colors
 
-buildroot=/tmp/hivebuild
 
 date
-
 echo -e $GREEN`pwd`$NOCOLOR
 
+#buildroot=/tmp/hivebuild
+buildroot=../hiveos-linux-packages
+if [[ ! -d $buildroot ]]; then
+	mkdir -p $buildroot
+	[[ $? -ne 0 ]] && echo "Error creating $buildroot" && exit 1
+fi
+buildroot=`realpath $buildroot`
+#echo $buildroot
 
-controls=`find . -name "control" | sort`
-controls=./hive/miners/claymore/control
+
+controls=$1
+[[ -z $controls ]] && echo "Usage: $0 all - build all packages, or specify package dir like hive/miners/claymore" && exit 1
+
+
+if [[ $controls == "all" ]]; then
+	controls=`find . -name "control" | sort`
+else
+	controls=./$controls/control
+	[[ ! -e $controls ]] && echo "$controls not found" && exit 1
+fi
+
 
 
 for control in $controls; do
@@ -30,14 +44,19 @@ for control in $controls; do
 	mkdir -p $pkgdir/DEBIAN
 	sudo chown -R $USER:`id -gn` $pkgdir #to make it able to write there when updating
 
-	cp $control $pkgdir/DEBIAN
+	cp -Lf $control $pkgdir/DEBIAN
+	if [[ $pkgname == "hive" ]]; then #special root hive package
+		cp -Lf hive/etc/apt/postinst $pkgdir/DEBIAN
+		cp -Lf hive/etc/apt/preinst $pkgdir/DEBIAN
+	fi
 
 	rsynctargetdir=$pkgdir/${sourcedir/.\//}
 	mkdir -p $rsynctargetdir
 
 	#find and exlude subdirs containting control file, these folders are subpackages
 	d=${sourcedir//\//\\\/}'\/' #escape replacement
-	find $sourcedir -mindepth 2 -name "control" -exec dirname {} \; | sed "s/$d//g" > $buildroot/tmp-exclude-from
+	echo ".DS_Store" > $buildroot/tmp-exclude-from
+	find $sourcedir -mindepth 2 -name "control" -exec dirname {} \; | sed "s/$d//g" >> $buildroot/tmp-exclude-from
 	rsync -av --exclude-from $buildroot/tmp-exclude-from --delete $sourcedir/ $rsynctargetdir/ > $buildroot/tmp-rsync.log #| tee $buildroot/tmp-rsync.log
 	changes=$(( `cat $buildroot/tmp-rsync.log | grep -v '^./$' | wc -l` - 4 ))
 	if [[ $changes > 0 ]]; then
