LINUX FIX use sshd port from iconfig in hardware watchdogs

diff --git a/hive/opt/qinheng/hl340 b/hive/opt/qinheng/hl340
--- a/hive/opt/qinheng/hl340
+++ b/hive/opt/qinheng/hl340
@@ -53,8 +53,27 @@ fi
 #if port 22 (ssh) responds then
 #send 60 second timeout to WD in HEX , if WD does not receive 2*timeout, then WD RESET the MB.
 
-while true; do
-	echo "Pinging watchdog"
-	[[ `nc -w 2 -zv localhost 22 2>&1 | grep -c succeeded` -gt 0 ]] && echo -ne $ping > $PORT
+#while true; do
+#	echo "Pinging watchdog"
+#	[[ `nc -w 2 -zv localhost 22 2>&1 | grep -c succeeded` -gt 0 ]] && echo -ne $ping > $PORT
+#	sleep 5
+#done
+
+pinging=1
+port=22
+while true
+do
+	t1=`date +%s` || t1=0
+	if [[ $pinging -eq 1 ]] && nc -w 1 -z localhost $port 2>&1; then
+		echo "Pinging watchdog"
+		echo -ne $ping > $PORT || break;
+	else
+		echo "NOT pinging watchdog (sshd port $port)"
+		port=`cat /etc/ssh/sshd_config 2>/dev/null | grep -oP "^Port[\s]+\K[0-9]+"`
+	fi
 	sleep 5
+	t2=`date +%s` || t2=0
+	[[ $t2 -eq 0 || $t1 -eq 0 || $(( t2 - t1 )) -ge 10 ]] && pinging=0 || pinging=1
 done
+
+message error "hl340 wd error"
