0.5-08

diff --git a/hive/bin/agent b/hive/bin/agent
--- a/hive/bin/agent
+++ b/hive/bin/agent
@@ -38,6 +38,16 @@ function miner_stats {
 			else
 				#[ "10.0 - ETH", "83", "67664;48;0", "28076;27236;12351", "891451;29;0", "421143;408550;61758", "67;40;70;45;69;34", "eth-eu1.nanopool.org:9999;sia-eu1.nanopool.org:7777", "0;0;0;0" ]
 				khs=`echo $stats | jq -r '.[2]' | awk -F';' '{print $1}'`
+				algo=`cat /hive/claymore/config.txt | grep -m1 --text "^\-dcoin" | sed 's/-dcoin //'`
+				stats=`echo "$stats" "[\"$algo\"]" | jq -s '.[0] + .[1]'` # push algo to end of array
+			fi
+		;;
+		claymore-x)
+			stats=`echo '{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}' | nc -w $API_TIMEOUT localhost 3337 | jq '.result'`
+			if [[ $? -ne 0  || -z stats ]]; then
+				echo -e "${YELLOW}Failed to read $miner stats from localhost:3337${NOCOLOR}"
+			else
+				khs=`echo $stats | jq -r '.[2]' | awk -F';' '{print $1/1000}'` #sols to khs
 			fi
 		;;
 		claymore-z)
@@ -66,19 +76,18 @@ function miner_stats {
 				echo -e "${YELLOW}Failed to read $miner stats from localhost:4068${NOCOLOR}"
 			else
 				summary=`echo "summary" | nc -w 2 localhost 4068`
-				re=';UPTIME=([0-9]+);' && [[ $summary =~ $re ]] && #&& echo "Matched" || echo "No match"
-					uptime=${BASH_REMATCH[1]}
-				re=';KHS=([0-9\.]+);' && [[ $summary =~ $re ]] && #&& echo "Matched" || echo "No match"
-					khs=${BASH_REMATCH[1]}
+				re=';UPTIME=([0-9]+);' && [[ $summary =~ $re ]] && uptime=${BASH_REMATCH[1]} #&& echo "Matched" || echo "No match"
+				re=';KHS=([0-9\.]+);' && [[ $summary =~ $re ]] && khs=${BASH_REMATCH[1]} #&& echo "Matched" || echo "No match"
+				algo=`echo "$summary" | tr ';' '\n' | grep -m1 'ALGO=' | sed -e 's/.*=//'`
 				#stats=`echo $threads | tr '|' '\n' | tr ';' '\n' | tr -cd '\11\12\15\40-\176' | grep -E 'KHS=' | sed -e 's/.*=//' | jq -cs '{khs:.}'`
-				striplines=`echo $threads | tr '|' '\n' | tr ';' '\n' | tr -cd '\11\12\15\40-\176'`
+				striplines=`echo "$threads" | tr '|' '\n' | tr ';' '\n' | tr -cd '\11\12\15\40-\176'`
 				#khs=`echo $striplines | grep -E 'KHS=' | sed -e 's/.*=//' | jq -cs '.'`
 				stats=$(jq -n \
-					--arg uptime "$uptime" \
+					--arg uptime "$uptime", --arg algo "$algo" \
 					--argjson khs "`echo \"$striplines\" | grep 'KHS=' | sed -e 's/.*=//' | jq -cs '.'`" \
 					--argjson temp "`echo \"$striplines\" | grep 'TEMP=' | sed -e 's/.*=//' | jq -cs '.'`" \
 					--argjson fan "`echo \"$striplines\" | grep 'FAN=' | sed -e 's/.*=//' | jq -cs '.'`" \
-					'{$khs, $temp, $fan, $uptime}')
+					'{$khs, $temp, $fan, $uptime, $algo}')
 			fi
 		;;
 		ethminer)
@@ -90,7 +99,7 @@ function miner_stats {
 				#`echo $stats | jq -r '.[3]' | awk 'gsub(";", "\n")' | jq -cs .` #send only hashes
 				stats=$(jq -n \
 					--arg uptime "`echo \"$stats\" | jq -r '.[1]' | awk '{print $1*60}'`" \
-					--argjson khs "`echo \"$stats\" | jq -r '.[3]' | awk 'gsub(";", "\n")' | jq -cs '.'`" \
+					--argjson khs "`echo \"$stats\" | jq -r '.[3]' | tr ';' '\n' | jq -cs '.'`" \
 					'{$khs, $uptime}')
 			fi
 		;;
diff --git a/hive/bin/hello b/hive/bin/hello
--- a/hive/bin/hello
+++ b/hive/bin/hello
@@ -24,6 +24,19 @@ mkdir -p "/hive-config/openvpn"
 
 HIVE_URL="$HIVE_HOST_URL/worker/api"
 
+
+#will need to restart miner after
+arg_restartminer=0
+#send boot flag with hello message
+arg_boot=0
+
+#check for arguments
+for var in "$@"
+do
+    [[ $var == "restartminer" ]] && arg_restartminer=1
+    [[ $var == "boot" ]] && arg_boot=1
+done
+
 # Make hello request ================================================================
 
 boot_time=`TZ='UTC' uptime -s`
@@ -50,6 +63,7 @@ jq -n \
 --arg rig_id "$RIG_ID" \
 --arg passwd "$RIG_PASSWD" \
 --arg boot_time "$boot_time" \
+--arg boot_event "$arg_boot" \
 --argjson ip "$ips_json" \
 --argjson gpu "$gpus_json" \
 --arg gpu_count_amd "$gpu_count_amd" \
@@ -65,7 +79,7 @@ jq -n \
 	"method": "hello", "jsonrpc": "2.0", "id": 0,
 	"params": {
 		$rig_id, $passwd,
-		$boot_time, $ip,
+		$boot_time, $boot_event, $ip,
 		$gpu, $gpu_count_amd, $gpu_count_nvidia,
 		"mb": {$manufacturer, $product}, "cpu": {$model, $cores, $aes},
 		$openvpn, $kernel, $version, $amd_version, $nvidia_version
@@ -92,7 +106,7 @@ error=$(echo $response | jq '.error' --raw-output)
 
 # Save config and check it ================================================================
 config=$(echo $response | jq '.result.config' --raw-output)
-[[ -z $config || $config == "null" ]] &&  echo -e "${RED}ERROR:${NOCOLOR} no config field:" && exit 1
+[[ -z $config || $config == "null" ]] &&  echo -e "${RED}ERROR:${NOCOLOR} no config field in response" && exit 1
 echo "$config" > $RIG_CONF
 . $RIG_CONF
 hostname-check
@@ -122,7 +136,7 @@ fi
 
 # Post actions =================================================================
 #restartminer - restart miner on success
-if [[ $1 == "restartminer" ]]; then
+if [[ $arg_restartminer == 1 ]]; then
 	miner restart
 	[[ $WD_ENABLED == 1 ]] &&
 		wd restart
diff --git a/hive/sbin/gpu-stats b/hive/sbin/gpu-stats
--- a/hive/sbin/gpu-stats
+++ b/hive/sbin/gpu-stats
@@ -55,19 +55,27 @@ function amd_stats {
 		busid=`realpath /sys/class/drm/card$cardno | rev | cut -d '/' -f 3 | rev`
 		busid=${busid#0000:} #trim prefix
 
-		fanmax=`head -1 $hwmondir/pwm1_max`
-		fan=`head -1 $hwmondir/pwm1`
-		temp=`head -1 $hwmondir/temp1_input`
+		speed="0"
+		[[ -e ${hwmondir}pwm1_max ]] && fanmax=`head -1 ${hwmondir}pwm1_max` || fanmax=0
 		if [ $fanmax -gt 0 ]; then
+			[[ -e ${hwmondir}pwm1 ]] && fan=`head -1 ${hwmondir}pwm1` || fan=0
 			speed=$(( fan * 100 / fanmax ))
-			temp=$(( temp / 1000 ))
 			#echo "GPU $cardno $busid ${temp}C $speed%"
 			#echo "${temp}, $speed"
-
-			putstats $busid $temp $speed
 		else
-			echo "Error: fanmax unknown for card $cardno"
+			echo "Error: fanmax unknown for card $cardno" >&2
 		fi
+
+		temp="0"
+		if [[ -e ${hwmondir}temp1_input ]]; then
+			temp=`head -1 ${hwmondir}temp1_input`
+			temp=$(( temp / 1000 ))
+		else
+			echo "Error: temp unknown for card $cardno" >&2
+		fi
+
+		putstats $busid $temp $speed
+
 
 		#cardcount=$(( cardcount + 1 ))
 	done
@@ -143,7 +151,7 @@ jq -c -n --argjson t "$jsontemps" --argjson f "$jsonfans" '{"temp": $t, "fan": $
 
 
 #
-#root@w163:~# nvidia-smi --query-gpu=index,timestamp,power.draw,clocks.sm,clocks.mem,clocks.gr --format=csv
+#root@w163:~# nvidia-smi --query-gpu=index,gpu_bus_id,gpu_name,power.draw,clocks.sm,clocks.mem,clocks.gr --format=csv
 #index, timestamp, power.draw [W], clocks.current.sm [MHz], clocks.current.memory [MHz], clocks.current.graphics [MHz]
 #0, 2017/10/04 00:54:27.644, 98.29 W, 1974 MHz, 4151 MHz, 1974 MHz
 #1, 2017/10/04 00:54:27.650, 138.22 W, 2075 MHz, 4252 MHz, 2075 MHz
