0.5-17

diff --git a/hive/bin/agent b/hive/bin/agent
--- a/hive/bin/agent
+++ b/hive/bin/agent
@@ -315,10 +315,11 @@ function do_command {
 		upgrade)
 			nohup bash -c '
 				payload=`selfupgrade 2>&1`
+				upgrade_exitcode=$?
 				echo "$payload"
-				[[ $? -eq 0 ]] &&
+				[[ $upgrade_exitcode -eq 0 ]] &&
 					echo "$payload" | message ok "Selfupgrade successful" payload ||
-					echo "$payload" | message error "Selfupgrade failed, please check log" payload
+					echo "$payload" | message error "Selfupgrade failed" payload
 			' > /tmp/nohup.log 2>&1 &
 		;;
 		exec)
