Beta 0.5

diff --git a/hive/bin/agent b/hive/bin/agent
--- a/hive/bin/agent
+++ b/hive/bin/agent
@@ -8,6 +8,8 @@ AMD_OC_CONF="/hive-config/amd-oc.conf"
 WALLET_CONF="/hive-config/wallet.conf"
 LOG="/var/log/hive-agent.log"
 
+API_TIMEOUT=15 #timeout to wait for miner API response, can take very long time on 13+ gpus
+
 [ -t 1 ] && . colors
 
 #$PPID - might be parent screen pid
@@ -20,57 +22,48 @@ screen_count=`screen -ls | grep "\.agent" | grep -v $PPID | wc -l`
 	exit 1
 
 
-function loop() {
-	date
+########################################################################################################################
 
-	[ ! -f $RIG_CONF ] && echo -e "No config $RIG_CONF" && return
-
-	#each time read config again
-	. $RIG_CONF
-
-	[ -z $MINER ] && MINER="claymore"
-	HIVE_URL="$HIVE_HOST_URL/worker/api"
-
-	gpu_stats=`gpu-stats`
-	temp=`echo $gpu_stats | jq '.temp'`
-	fan=`echo $gpu_stats | jq '.fan'`
+function miner_stats {
+	local miner=$1
+	local mindex=$2 #empty or 2
 
 	khs=0
 	stats=
-	case $MINER in
+	case $miner in
 		claymore)
-			stats=`echo '{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}' | nc -w 2 localhost 3333 | jq '.result'`
-			if [ $? -ne 0 ]; then
-				echo -e "${YELLOW}Failed to read Claymore stats from localhost:3333${NOCOLOR}"
+			stats=`echo '{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}' | nc -w $API_TIMEOUT localhost 3333 | jq '.result'`
+			if [[ $? -ne 0  || -z stats ]]; then
+				echo -e "${YELLOW}Failed to read $miner stats from localhost:3333${NOCOLOR}"
 			else
 				#[ "10.0 - ETH", "83", "67664;48;0", "28076;27236;12351", "891451;29;0", "421143;408550;61758", "67;40;70;45;69;34", "eth-eu1.nanopool.org:9999;sia-eu1.nanopool.org:7777", "0;0;0;0" ]
 				khs=`echo $stats | jq -r '.[2]' | awk -F';' '{print $1}'`
 			fi
 		;;
 		claymore-z)
-			stats=`echo '{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}' | nc -w 2 localhost 3335 | jq '.result'`
-			if [ $? -ne 0 ]; then
-				echo -e "${YELLOW}Failed to read Claymore Z stats from localhost:3335${NOCOLOR}"
+			stats=`echo '{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}' | nc -w $API_TIMEOUT localhost 3335 | jq '.result'`
+			if [[ $? -ne 0  || -z stats ]]; then
+				echo -e "${YELLOW}Failed to read $miner stats from localhost:3335${NOCOLOR}"
 			else
 				khs=`echo $stats | jq -r '.[2]' | awk -F';' '{print $1/1000}'` #sols to khs
 			fi
 		;;
 		ewbf)
 			#0000:03:00.0, .result[].busid[5:] trims first 5 chars
-			#stats_raw=`curl --connect-timeout 2 --max-time 5 --silent http://localhost:42000/getstat`
+			#stats_raw=`curl --connect-timeout 2 --max-time $API_TIMEOUT --silent --noproxy '*' http://localhost:42000/getstat`
 			#curl uses http_proxy env var, we don't need it. --noproxy does not work
-			stats_raw=`echo "GET /getstat" | nc -w 2 localhost 42000 | tail -n 1`
-			if [ $? -ne 0 ]; then
-				echo -e "${YELLOW}Failed to read EWBF stats from localhost:42000${NOCOLOR}"
+			stats_raw=`echo "GET /getstat" | nc -w $API_TIMEOUT localhost 42000 | tail -n 1`
+			if [[ $? -ne 0  || -z stats_raw ]]; then
+				echo -e "${YELLOW}Failed to read $miner stats from localhost:42000${NOCOLOR}"
 			else
 				stats=`echo $stats_raw | jq -c '{speed_sps: [.result[].speed_sps], busid: [.result[].busid[5:]|ascii_downcase], start_time: .result[0].start_time}'`
 				khs=`echo $stats_raw | jq -r '.result[].speed_sps' | awk '{s+=$1} END {print s/1000}'` #sum up and convert to khs
 			fi
 		;;
 		ccminer)
-			threads=`echo "threads" | nc -w 2 localhost 4068` #&& echo $threads
-			if [ $? -ne 0 ]; then
-				echo -e "${YELLOW}Failed to read CCMINER stats from localhost:4068${NOCOLOR}"
+			threads=`echo "threads" | nc -w $API_TIMEOUT localhost 4068` #&& echo $threads
+			if [[ $? -ne 0  || -z threads ]]; then
+				echo -e "${YELLOW}Failed to read $miner stats from localhost:4068${NOCOLOR}"
 			else
 				summary=`echo "summary" | nc -w 2 localhost 4068`
 				re=';UPTIME=([0-9]+);' && [[ $summary =~ $re ]] && #&& echo "Matched" || echo "No match"
@@ -89,9 +82,9 @@ function loop() {
 			fi
 		;;
 		ethminer)
-			stats=`echo '{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}' | nc -w 2 localhost 3334 | jq '.result'`
-			if [ $? -ne 0 ]; then
-				echo -e "${YELLOW}Failed to read ethminer stats from localhost:3334${NOCOLOR}"
+			stats=`echo '{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}' | nc -w $API_TIMEOUT localhost 3334 | jq '.result'`
+			if [[ $? -ne 0  || -z stats ]]; then
+				echo -e "${YELLOW}Failed to read $miner stats from localhost:3334${NOCOLOR}"
 			else
 				khs=`echo $stats | jq -r '.[2]' | awk -F';' '{print $1}'`
 				#`echo $stats | jq -r '.[3]' | awk 'gsub(";", "\n")' | jq -cs .` #send only hashes
@@ -101,17 +94,91 @@ function loop() {
 					'{$khs, $uptime}')
 			fi
 		;;
+		sgminer-gm)
+			stats_raw=`echo '{"command":"summary+devs"}' | nc -w $API_TIMEOUT localhost 4028`
+			if [[ $? -ne 0 || -z stats_raw ]]; then
+				echo -e "${YELLOW}Failed to read $miner from localhost:4028${NOCOLOR}"
+			else
+				khs=`echo $stats_raw | jq '.["summary"][0]["SUMMARY"][0]["KHS 15s"]'`
+				stats=`echo $stats_raw | jq '{khs: [.devs[0].DEVS[]."KHS 15s"], temp: [.devs[0].DEVS[].Temperature], \
+						fan: [.devs[0].DEVS[]."Fan Percent"], uptime: .summary[0].SUMMARY[0].Elapsed, algo: "'$SGMINER_GM_ALGO'"}'`
+			fi
+		;;
+		dstm)
+			stats_raw=`echo '{"id":1, "method":"getstat"}' | nc -w $API_TIMEOUT localhost 43000`
+			if [[ $? -ne 0 || -z stats_raw ]]; then
+				echo -e "${YELLOW}Failed to read $miner from localhost:43000${NOCOLOR}"
+			else
+				khs=`echo $stats_raw | jq '.result[].sol_ps' | awk '{s+=$1} END {print s/1000}'`
+				uptime=$(( `date +%s` - $(stat -c%X /proc/`pidof zm`) )) #dont think zm will die so soon after getting stats
+				nvidiastats=`gpu-stats nvidia` #a bit overhead in calling nvidia-smi again, shame on dstm, he gives no temps
+				#stats=`echo $stats_raw | jq '{ hs: [.result[].sol_ps], temp: [.result[].temperature], uptime: "'$uptime'"}'`
+				stats=`echo $stats_raw | jq '{ hs: [.result[].sol_ps], uptime: "'$uptime'"}'`
+				stats=`echo "$stats $nvidiastats" | jq -s '.[0] * .[1]'`
+			fi
+		;;
+		xmr-stak-cpu)
+			stats_raw=`curl --connect-timeout 2 --max-time $API_TIMEOUT --silent --noproxy '*' http://127.0.0.1:60044/api.json`
+			if [[ $? -ne 0 || -z stats_raw ]]; then
+				echo -e "${YELLOW}Failed to read $miner from localhost:60044${NOCOLOR}"
+			else
+				khs=`echo $stats_raw | jq -r '.hashrate.total[0]' | awk '{print $1/1000}'`
+				#to do : lm-sensors
+				coretemps=`cat /sys/class/thermal/thermal_zone*/temp | head -n $(nproc) | awk '{print $1/1000}' | jq -rsc .` #just a try to get CPU temps
+				stats=`echo $stats_raw | jq '{hs: [.hashrate.threads[][0]], temp: '$coretemps', uptime: .connection.uptime}'`
+			fi
+		;;
 		*)
-			MINER="unknown"
+			miner="unknown"
+			#MINER=miner
+			eval "MINER${mindex}=unknown"
 		;;
 	esac
 
 
 	[[ -z $khs ]] && khs=0
-	echo -e "Total hashrate `[[ $khs > 0 ]] && echo -e ${YELLOW} || echo -e ${RED}`$khs${NOCOLOR} kH/s"
-	echo $khs > /tmp/khs
-
 	[[ -z $stats ]] && stats="null"
+
+#	[[ ! -z $mindex ]] &&
+#		eval "khs${mindex}"
+}
+
+
+########################################################################################################################
+
+function loop {
+	date
+
+	[ ! -f $RIG_CONF ] && echo -e "No config $RIG_CONF" && return
+
+	#each time read config again
+	. $RIG_CONF
+	. $WALLET_CONF
+
+	[ -z $MINER ] && MINER="claymore"
+	HIVE_URL="$HIVE_HOST_URL/worker/api"
+
+	gpu_stats=`gpu-stats`
+	temp=`echo $gpu_stats | jq '.temp'`
+	fan=`echo $gpu_stats | jq '.fan'`
+
+
+	miner2_json=
+	if [[ ! -z $MINER2 ]]; then
+		miner_stats $MINER2 2
+		khs2=$khs
+		miner2_json=$(jq -n --arg miner2 "$MINER2" --arg total_khs2 "$khs" --argjson miner_stats2 "$stats" \
+			'{"params": {$miner2, $total_khs2, $miner_stats2}}')
+	fi
+
+	miner_stats $MINER #khs and stats are global
+
+	echo -en "Hashrate ${CYAN}$MINER${NOCOLOR} `[[ $khs > 0 ]] && echo -e ${YELLOW} || echo -e ${RED}`$khs${NOCOLOR} kH/s"
+	[[ ! -z $MINER2 ]] &&
+		echo -en " ${CYAN}$MINER2${NOCOLOR} `[[ $khs2 > 0 ]] && echo -e ${YELLOW} || echo -e ${RED}`$khs2${NOCOLOR} kH/s"
+	echo -en "\n"
+	echo $khs > /run/hive/khs
+
 
 
 	#echo $stats
@@ -136,6 +203,9 @@ function loop() {
 		}
 	}'
 	)
+
+	[[ ! -z $miner2_json ]] && #add miner2 stats to json
+		request=`echo "$request" "$miner2_json" | jq -s '.[0] * .[1]'`
 
 	echo $request | jq '.' -c
 
@@ -181,9 +251,9 @@ function loop() {
 }
 
 
+########################################################################################################################
 
-
-function do_command() {
+function do_command {
 	#body=$1
 	[[ -z $command ]] && command=`echo $body | jq -r '.command'` #get command for batch
 
@@ -192,14 +262,14 @@ function do_command() {
 			echo -e "${BGREEN}$command${NOCOLOR}"
 		;;
 		reboot)
-			message ok "Rebooting..." 120
-			echo -e "${BRED}Rebooting...${NOCOLOR}"
+			message ok "Rebooting" 120
+			echo -e "${BRED}Rebooting${NOCOLOR}"
 			nohup bash -c 'sreboot' > /tmp/nohup.log 2>&1 &
 			#superreboot
 		;;
 		upgrade)
 			nohup bash -c '
-				payload=`selfupgrade`
+				payload=`selfupgrade 2>&1`
 				echo "$payload"
 				[[ $? -eq 0 ]] &&
 					echo "$payload" | message ok "Selfupgrade successful" payload ||
@@ -246,9 +316,15 @@ function do_command() {
 					#after this there will be new password on server, so all new request should use new one
 				fi
 
-				#just apply new config
+				#Write new config and load it
 				echo "$config" > $RIG_CONF
 				. $RIG_CONF
+
+				#Save wallet if given
+				wallet=$(echo $body | jq '.wallet' --raw-output)
+				[[ ! -z $wallet && $wallet != "null" ]] &&
+					echo "$wallet" > $WALLET_CONF
+
 
 				justwrite=$(echo $body | jq '.justwrite' --raw-output)
 
@@ -281,7 +357,7 @@ function do_command() {
 			if [[ ! -z $nvidia_oc && $nvidia_oc != "null" ]]; then
 				echo "$nvidia_oc" > $NVIDIA_OC_CONF
 				nohup bash -c '
-					nvidia-oc > /var/log/nvidia-oc.log 2>&1
+					nvidia-oc-log
 					exitcode=$?
 					payload=`cat /var/log/nvidia-oc.log`
 					echo "$payload"
@@ -298,7 +374,7 @@ function do_command() {
 			if [[ ! -z $amd_oc && $amd_oc != "null" ]]; then
 				echo "$amd_oc" > $AMD_OC_CONF
 				nohup bash -c '
-					amd-oc > /var/log/amd-oc.log 2>&1
+					amd-oc-safe
 					exitcode=$?
 					payload=`cat /var/log/amd-oc.log`
 					echo "$payload"
@@ -399,11 +475,22 @@ function do_command() {
 
 
 
+########################################################################################################################
 
 
 while true
 do
+	time_start=`date +%s`
 	loop
+	time_finish=`date +%s`
+
+	wasted=$(( $time_finish - $time_start ))
+
+	tosleep=$(( $INTERVAL - $wasted ))
+
+	#echo "Sleeping $tosleep"
 	echo ""
-	sleep $INTERVAL
+
+	[[ $tosleep > 0 ]] &&
+		sleep $INTERVAL
 done
diff --git a/hive/sbin/gpu-stats b/hive/sbin/gpu-stats
--- a/hive/sbin/gpu-stats
+++ b/hive/sbin/gpu-stats
@@ -1,6 +1,9 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #GPU temps and fans
 #Sorted by pci bus id. It was hard...
+
+###Usage: gpu-stats internal|amd|nvidia
+
 
 
 temps=()
@@ -8,14 +11,28 @@ fans=()
 
 bus_temp_fan=()
 
+#bus temp fan
 function putstats {
 	#echo $1
 	#echo $2
 	#temps+=($1)
 	#fans+=($2)
-	bus_temp_fan+=("$3 $1 $2")
+	bus_temp_fan+=("$1 $2 $3")
 }
 
+
+function internal_stats {
+	#detect not NVIDIA and not AMD cards, might be only one internal
+	local cards=`lspci | grep -E "VGA|3D controller" | grep -vE "NVIDIA|AMD"`
+	while read -r line; do
+		[[ -z $line ]] && continue
+
+		busid=`echo $line | awk '{print $1}'`
+
+		[[ ! -z $busid ]] &&
+			putstats $busid "0" "0"
+	done <<< "$cards"
+}
 
 #AMD cards stats
 function amd_stats {
@@ -47,7 +64,7 @@ function amd_stats {
 			#echo "GPU $cardno $busid ${temp}C $speed%"
 			#echo "${temp}, $speed"
 
-			putstats $temp $speed $busid
+			putstats $busid $temp $speed
 		else
 			echo "Error: fanmax unknown for card $cardno"
 		fi
@@ -56,12 +73,17 @@ function amd_stats {
 	done
 }
 
-function nv_stats {
+function nvidia_stats {
 	#72, 81, 00000000:01:00.0
 	#71, 54, 00000000:03:00.0
 	#68, 46, 00000000:06:00.0
 	#68, 83, 00000000:07:00.0
 	stats=`timeout -s9 2 nvidia-smi --format=csv,noheader,nounits --query-gpu=temperature.gpu,fan.speed,gpu_bus_id`
+
+	[[ $? > 0 ]] && return
+
+	#stats='Unable to determine the device handle for GPU 0000:05:00.0: GPU is lost. Reboot the system to recover this GPU'
+	#Exec failed, exitcode=15
 
 	#NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
 	[[ $stats =~ NVIDIA-SMI ]] && return
@@ -76,12 +98,23 @@ function nv_stats {
 		#echo ${params[0]}
 		#echo ${params[1]}
 		busid=${params[2]#00000000:} #trim prefix
-		putstats ${params[0]} ${params[1]} $busid
+
+		#echo "NVIDIA $busid ${params[0]} ${params[1]}"
+		putstats $busid ${params[0]} ${params[1]}
 	done <<<"$stats"
 }
 
-amd_stats
-nv_stats
+
+function all_stats {
+	internal_stats
+	amd_stats
+	nvidia_stats
+}
+
+
+[[ -z $1 ]] &&
+	all_stats ||
+	eval ${1}_stats
 
 #echo "# ${#bus_temp_fan[@]}"
 #echo "* ${bus_temp_fan[*]}"
