modify agent and miner scripts for suppoer cpuminer-opt miner

diff --git a/hive/bin/agent b/hive/bin/agent
--- a/hive/bin/agent
+++ b/hive/bin/agent
@@ -308,6 +308,63 @@ function miner_stats {
 				stats=`echo $stats_raw | jq '{hs: [.hashrate.threads[][0]], temp: '$cpu_temp', uptime: .connection.uptime}'`
 			fi
 		;;
+		cpuminer-opt)
+			threads=`echo "threads" | nc -w $API_TIMEOUT localhost 4048` #&& echo $threads
+			if [[ $? -ne 0  || -z $threads ]]; then
+				echo -e "${YELLOW}Failed to read $miner stats from localhost:4048${NOCOLOR}"
+			else
+				summary=`echo "summary" | nc -w $API_TIMEOUT localhost 4048`
+#				echo $summary
+				re=';UPTIME=([0-9]+);' && [[ $summary =~ $re ]] && local uptime=${BASH_REMATCH[1]} #&& echo "Matched" || echo "No match"
+				#khs will calculate from cards; re=';KHS=([0-9\.]+);' && [[ $summary =~ $re ]] && khs=${BASH_REMATCH[1]} #&& echo "Matched" || echo "No match"
+				vers=`echo "$summary" | tr ';' '\n' | grep -m1 'VER=' | sed -e 's/.*=//'`
+				algo=`echo "$summary" | tr ';' '\n' | grep -m1 'ALGO=' | sed -e 's/.*=//'`
+				acc=`echo "$summary" | tr ';' '\n' | grep -m1 'ACC=' | sed -e 's/.*=//'`
+				rej=`echo "$summary" | tr ';' '\n' | grep -m1 'REJ=' | sed -e 's/.*=//'`
+				striplines=`echo "$threads" | tr "|" "\n" | tr ";" "\n" | tr -cd '\11\12\15\40-\176'` 
+				hashes_val=(`echo "$striplines" | grep -E "H/s=" | sed -e 's/.*=//'`)
+				hashes_pre=(`echo "$striplines" | grep -E "H/s=" | sed -e 's/H.*//'`)
+				total_hs=0
+				kilo=1000
+				for (( i=0; i < ${#hashes_val[@]}; i++ )); do
+					smb=${hashes_pre[$i]}
+					case "$smb" in
+						k)
+						# kH/s - quark
+						koef=$kilo
+						;;
+						M)
+						# MH/s - blake2s
+						koef=$((kilo*kilo))
+						;;
+						G)
+						# GH/s - not found but who's know
+						koef=$((kilo*kilo*kilo))
+						;;
+						*)
+						#  H/s - yescrypt
+						koef=1
+						;;
+					esac
+
+					hs[$i]=`echo ${hashes_val[$i]} | awk -v koef=$koef '{print $1*koef}' | awk '{ printf("%.f",$1) }'`
+					total_hs=$(($total_hs+${hs[$i]}))
+					# It's temporary solution
+					temps[$i]=`echo "$summary" | tr ';' '\n' | grep -m1 'TEMP=' | sed -e 's/.*=//'`
+#					temps[$i]=`sensors coretemp-* | grep "Package id" | awk '{print $4}' | sed 's/.+*//' | sed 's/\..*//'`
+				done
+				# Convert total H/s to kH/s
+				khs=`echo $total_hs | awk -F';' '{print $1/1000}'` #hashes to khs
+
+				stats=$(jq -n \
+					--arg vers "$vers" \
+					--arg acc "$acc" --arg rej "$rej" \
+					--arg uptime "$uptime" --arg algo "$algo" \
+					--argjson hs "`echo ${hs[@]} | tr " " "\n" | jq -cs '.'`" \
+					--argjson temp "`echo ${temps[@]} | tr " " "\n" | jq -cs '.'`" \
+					'{$vers, $algo, $hs, $acc, $rej, $temp, $uptime}')
+			fi
+		;;
 		*)
 			miner="unknown"
 			#MINER=miner
