0.5-04

diff --git a/hive/bin/ewbf b/hive/bin/ewbf
--- a/hive/bin/ewbf
+++ b/hive/bin/ewbf
@@ -13,6 +13,7 @@ THIS_MINER_NAME="ewbf"
 function config_gen() {
 	RIG_CONF="/hive-config/rig.conf"
 	WALLET_CONF="/hive-config/wallet.conf"
+	EWBF_GLOBAL_CONFIG="/hive/ewbf/miner.global.cfg"
 	EWBF_CONFIG="/hive/ewbf/miner.cfg"
 
 	[ ! -f $RIG_CONF ] && echo -e "${RED}No rig config $RIG_CONF${NOCOLOR}" && return 1
@@ -21,12 +22,21 @@ function config_gen() {
 	. $RIG_CONF
 	. $WALLET_CONF
 
-	[[ -z $WORKER_NAME ]] && echo "ERROR: No WORKER_NAME set" && return 1
+	#[[ -z $WORKER_NAME ]] && echo "${RED}ERROR: No WORKER_NAME set${NOCOLOR}" && return 1
 
+	cat $EWBF_GLOBAL_CONFIG > $EWBF_CONFIG
 
-	[[ ! -z $ZSERVER ]] && sed -i "s/^server .*/server $ZSERVER/g" $EWBF_CONFIG || echo "ZSERVER not set"
-	[[ ! -z $ZPORT ]] && sed -i "s/^port .*/port $ZPORT/g" $EWBF_CONFIG || echo "ZPORT not set"
-	[[ ! -z $ZPASS ]] && sed -i "s/^pass .*/pass $ZPASS/g" $EWBF_CONFIG || echo "ZPASS not set"
+	[[ ! -z $EWBF_USER_CONFIG ]] && echo -e "#USER CONFIG\n$EWBF_USER_CONFIG" >> $EWBF_CONFIG
+
+	echo -e "\n[server]"  >> $EWBF_CONFIG
+
+#	[[ ! -z $ZSERVER ]] && sed -i "s/^server .*/server $ZSERVER/g" $EWBF_CONFIG || echo "${RED}ZSERVER not set${NOCOLOR}"
+#	[[ ! -z $ZPORT ]] && sed -i "s/^port .*/port $ZPORT/g" $EWBF_CONFIG || echo "${RED}ZPORT not set${NOCOLOR}"
+#	[[ ! -z $ZPASS ]] && sed -i "s/^pass .*/pass $ZPASS/g" $EWBF_CONFIG || echo "${RED}ZPASS not set${NOCOLOR}"
+
+	[[ ! -z $ZSERVER ]] && echo "server $ZSERVER" >>  $EWBF_CONFIG || echo "${RED}ZSERVER not set${NOCOLOR}"
+	[[ ! -z $ZPORT ]] && echo "port $ZPORT" >> $EWBF_CONFIG || echo "${RED}ZPORT not set${NOCOLOR}"
+	[[ ! -z $ZPASS ]] && echo "pass $ZPASS" >> $EWBF_CONFIG || echo "${RED}ZPASS not set${NOCOLOR}"
 
 
 	#[[ -z $ZWAL ]] && echo -e "${RED}ZWAL not set{NOCOLOR}"
@@ -34,20 +44,15 @@ function config_gen() {
 	if [[ -z $ZTEMPLATE ]]; then
 		echo -e "${RED}ZTEMPLATE not set{NOCOLOR}"
 	else
-		[[ ! -z $ZWAL ]] && ZTEMPLATE=${ZTEMPLATE/\%ZWAL\%/$ZWAL} || "${RED}ZWAL not set${NOCOLOR}"
-		[[ ! -z $WORKER_NAME ]] && ZTEMPLATE=${ZTEMPLATE/\%WORKER_NAME\%/$WORKER_NAME} || echo "${RED}WORKER_NAME not set${NOCOLOR}";
+		[[ ! -z $ZWAL ]] && ZTEMPLATE=${ZTEMPLATE/\%ZWAL\%/$ZWAL} #|| "${RED}ZWAL not set${NOCOLOR}"
+		[[ ! -z $WORKER_NAME ]] && ZTEMPLATE=${ZTEMPLATE/\%WORKER_NAME\%/$WORKER_NAME} #|| echo "${RED}WORKER_NAME not set${NOCOLOR}";
 		[[ ! -z $EMAIL ]] && ZTEMPLATE=${ZTEMPLATE/\%EMAIL\%/$EMAIL} #|| echo "EMAIL not set";
 
 		#escape variable
-		ZTEMPLATE=$(sed 's/[]\/$*.^|[]/\\&/g' <<<"$ZTEMPLATE")
-		sed -i "s/^user .*/user $ZTEMPLATE/g" $EWBF_CONFIG
+		#ZTEMPLATE=$(sed 's/[]\/$*.^|[]/\\&/g' <<<"$ZTEMPLATE")
+		#sed -i "s/^user .*/user $ZTEMPLATE/g" $EWBF_CONFIG
+		echo "user $ZTEMPLATE" >> $EWBF_CONFIG
 	fi
-
-	#ZWAL="t1VS4MURTc5HxV3Hm85HsCXRHHN5Etss9vH"
-	#ZSERVER="zec-eu1.nanopool.org"
-	#ZTEMPLATE="%ZWAL%/%WORKER_NAME%/%EMAIL%"
-	#ZPORT="6666"
-	#ZPASS="z"
 
 	#[server]
 	#server zec-eu1.nanopool.org
@@ -68,7 +73,7 @@ do
 		killcx $con lo
 	done
 
-	miner logrotate $THIS_MINER_NAME
+	/hive/bin/miner logrotate $THIS_MINER_NAME
 	/hive/$THIS_MINER_NAME/miner
 	echo ""
 	echo -e "${YELLOW}$THIS_MINER_NAME exited, waiting to cooldown a bit${NOCOLOR}"
diff --git a/hive/bin/selfupgrade b/hive/bin/selfupgrade
--- a/hive/bin/selfupgrade
+++ b/hive/bin/selfupgrade
@@ -1,23 +1,32 @@
 #!/usr/bin/env bash
 
+. colors
+
 #remove stupid rep file for smaller updates
-[[ -f /etc/apt/sources.list.d/amdgpu-pro.list ]] && /etc/apt/sources.list.d/amdgpu-pro.list
+[[ -f /etc/apt/sources.list.d/amdgpu-pro.list ]] && rm /etc/apt/sources.list.d/amdgpu-pro.list
+
+
+#Sometimes Ubuntu fails to update repos
+dpkg --configure -a
+
 
 #apt-get update -o Dir::Etc::sourcelist=hiverepo.list
 #apt-get update
 apt-get update -o Dir::Etc::sourcelist="sources.list.d/hiverepo.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
-[[ $? -ne 0 ]] && exit $?
+exitcode=$?
+[[ $exitcode -ne 0 ]] && echo -e "${RED}Repository update failed${NOCOLOR}" && exit $exitcode
 
 
 updateavail=`apt list --upgradable 2>&1 | grep hive | wc -l`
 [[ $updateavail == 0 ]] &&
-	echo "Hive is up to date already" &&
+	echo -e "${GREEN}Hive is up to date already${NOCOLOR}" &&
 	exit 0
 
 echo ------------------------------------------------------
 
 apt-get upgrade -y hive
-[[ $? -ne 0 ]] && echo "selfupgrade: apt-get upgrade failed" && exit $?
+exitcode=$?
+[[ $exitcode -ne 0 ]] && echo -e "${RED}Upgrade failed${NOCOLOR}" && exit $exitcode
 
 echo ------------------------------------------------------
 
@@ -30,15 +39,19 @@ apt-get clean
 
 #echo ------------------------------------------------------
 #Moved from postinst again as hello need to see new version
-echo "> Saying hello to server again"
+echo -e "${YELLOW}> Saying hello to server again${NOCOLOR}"
 hello restartminer
 #miner restart
 #wd restart
 
 
 #Restart agent
-echo "> Restarting agent"
+echo -e "${YELLOW}> Restarting agent${NOCOLOR}"
 screen -S agent -X quit
 agent-screen
+
+
+echo -e "${GREEN}Upgrade complete. Have a happy mining.${NOCOLOR}"
+
 
 exit 0
