0.5-65 net-test check api response

diff --git a/hive/bin/net-test b/hive/bin/net-test
--- a/hive/bin/net-test
+++ b/hive/bin/net-test
@@ -32,57 +32,81 @@ function PrintCase {
 
 # ping wrapper
 function Ping {
-	LAST_RESULT=0
-    IP=$2
+	local LAST_RESULT=0
+	local IP=$2
     [ -z ${IP} ] && IP=$1
 
     PrintCase "ping $1"
-    ping -q -c 1 -w 5 $IP > /dev/null 2>&1 && echo -e $OK || { LAST_RESULT=1; echo -e $FAIL; }
+    ping -q -c 1 -w 5 $IP > /dev/null 2>&1
+    LAST_RESULT=$?
+    [[ $LAST_RESULT == 0 ]] && echo -e $OK || echo -e $FAIL
     return $LAST_RESULT
 }
 
 
 # curl wrapper
 function Curl {
-	LAST_RESULT=0
-    IP=$2
+	local LAST_RESULT=0
+    local checkApi=$2
+    local IP=
     [ -z ${IP} ] && IP=$1
 
     PrintCase "curl $1"
-    curl curl --insecure --connect-timeout 4 --max-time 10 $IP > /dev/null 2>&1 && echo -e $OK || { LAST_RESULT=1; echo -e $FAIL; }
+    [[ $checkApi != "api" ]] &&
+    	local response=`curl --insecure --connect-timeout 4 --max-time 10 --silent $IP` ||  #> /dev/null 2>&1
+    	local response=`curl --insecure --connect-timeout 4 --max-time 10 --silent \
+    			-H "Content-Type: application/json" \
+    			-X POST -d '{"method":"stats", "params": {"rig_id":"-1", "passwd": "1"}}' \
+    			$IP/worker/api`
+
+    LAST_RESULT=$?
+    if [[ $LAST_RESULT == 0 ]]; then
+    	if [[ $checkApi != "api" ]]; then
+    		echo -e $OK
+		else
+			local respCheck=`echo "$response" | jq .error.code 2>/dev/null`
+			[[ $respCheck == '' || $respCheck == 'null' ]] && echo -e $FAIL || echo -e $OK
+		fi
+    else
+    	echo -e $FAIL
+    fi
+
     return $LAST_RESULT
 }
 
 
 # nslookup wrapper
 function NSLookup {
-	LAST_RESULT=0
-    IP=$2
+	local LAST_RESULT=0
+	local IP=
     [ -z ${IP} ] && IP=$1
 
     PrintCase "nslookup $1"
-    nslookup $IP > /dev/null 2>&1 && echo -e $OK || { LAST_RESULT=1; echo -e $FAIL; }
+    nslookup $IP > /dev/null 2>&1
+    LAST_RESULT=$?
+    [[ $LAST_RESULT == 0 ]] && echo -e $OK || echo -e $FAIL
     return $LAST_RESULT
 }
 
 
 # check host with dns resolving, ip, http, https cases
 function Connection {
-	LAST_RESULT=0
-    RESULT=0
-    host=$1
+	local LAST_RESULT=0
+    local RESULT=0
+    local host=$1
+    local checkApi=$2
 
-    NSLookup $1 $2
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Please check your DNS server $DNS"$NOCOLOR
+    NSLookup $1
+    [ $? -ne 0 ] && echo -e $ERROR_COLOR"Please check your DNS server $DNS"$NOCOLOR
 
-    Ping $1 $2
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Please check your connection settings"$NOCOLOR
+    Ping $1
+    [ $? -ne 0 ] && echo -e $ERROR_COLOR"Please check your connection settings"$NOCOLOR
 
-    Curl "http://$1" $2
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"HTTP connection failed. Please check Firewall rules or connection setup."$NOCOLOR
+    Curl "http://$1" $checkApi
+    [ $? -ne 0 ] && echo -e $ERROR_COLOR"HTTP connection failed. Please check Firewall rules or connection setup."$NOCOLOR
 
-    Curl "https://$1" $2
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"HTTPS (SSL) connection failed. Please check Firewall rules or connection setup."$NOCOLOR
+    Curl "https://$1" $checkApi
+    [ $? -ne 0 ] && echo -e $ERROR_COLOR"HTTPS (SSL) connection failed. Please check Firewall rules or connection setup."$NOCOLOR
 
 	return $LAST_RESULT
 }
@@ -92,13 +116,13 @@ function Connection {
 function Connections {
     echo -e "${YELLOW}Checking network connection:${NOCOLOR}"
     Ping "$LOCAL_GW (Gateway)" $LOCAL_GW
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Failed to ping router. Please check your router and physical connection."$NOCOLOR
+    [ $? -ne 0 ] && echo -e $ERROR_COLOR"Failed to ping router. Please check your router and physical connection."$NOCOLOR
 
     Ping "$LOCAL_DNS (DNS)" $LOCAL_DNS
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Please check your DNS server $LOCAL_DNS"$NOCOLOR
+    [ $? -ne 0 ] && echo -e $ERROR_COLOR"Please check your DNS server $LOCAL_DNS"$NOCOLOR
 
     Ping "1.1.1.1 (Cloudflare)" "1.1.1.1"
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Failed to ping Google DNS. Please check your internet connection"$NOCOLOR
+    [ $? -ne 0 ] && echo -e $ERROR_COLOR"Failed to ping Google DNS. Please check your internet connection"$NOCOLOR
 
     Connection "hiveos.farm"
 
@@ -107,18 +131,18 @@ function Connections {
     echo -e "${YELLOW}Checking connection to Hive servers:${NOCOLOR}"
 	echo
     echo -e "${WHITE}>>> api.hiveos.farm${NOCOLOR}"
-    Connection "api.hiveos.farm"
-    Curl "https://api.hiveos.farm:8443" $2; [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"HTTPS (SSL) on port 8443 connection failed. Please check Firewall rules or connection setup."$NOCOLOR
-    #Curl "https://api.hiveos.farm:41282" $2; [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"HTTPS (SSL) connection on port 41282 failed. Please check Firewall rules or connection setup."$NOCOLOR
+    Connection "api.hiveos.farm" api
+    Curl "https://api.hiveos.farm:8443" $2
+    [[ $? -ne 0 ]] && echo -e "${ERROR_COLOR}HTTPS (SSL) on port 8443 connection failed. Please check Firewall rules or connection setup.${NOCOLOR}"
 	echo
     echo -e "${WHITE}>>> paris.hiveos.farm${NOCOLOR}"
-    Connection "paris.hiveos.farm"
+    Connection "paris.hiveos.farm" api
 	echo
     echo -e "${WHITE}>>> amster.hiveos.farm${NOCOLOR}"
-    Connection "amster.hiveos.farm"
+    Connection "amster.hiveos.farm" api
 	echo
     echo -e "${WHITE}>>> helsinki.hiveos.farm${NOCOLOR}"
-    Connection "helsinki.hiveos.farm"
+    Connection "helsinki.hiveos.farm" api
 }
 
 
