LINUX ADD net-test - added api-c.hiveos.farm

diff --git a/hive/bin/net-test b/hive/bin/net-test
--- a/hive/bin/net-test
+++ b/hive/bin/net-test
@@ -4,7 +4,7 @@
 [[ -e $RIG_CONF ]] && . $RIG_CONF
 
 # hosts on ports 80 and 443
-API_HOSTS=("api.hiveos.farm" "helsinki.hiveos.farm" "msk.hiveos.farm" "ca1.hiveos.farm" "paris.hiveos.farm" "amster.hiveos.farm")
+API_HOSTS=("api.hiveos.farm" "api-cf.hiveos.farm" "helsinki.hiveos.farm" "msk.hiveos.farm" "ca1.hiveos.farm" "paris.hiveos.farm" "amster.hiveos.farm")
 # urls for other ports
 API_URLS=("https://api.hiveos.farm:8443" "http://helsinki.hiveos.farm:8000")
 # just to check connection
@@ -36,7 +36,7 @@ LOCAL_IP=`hostname -I | awk '{print $1}'`
 LOCAL_GW=`ip route | awk '/default/ { print $3 }'`
 
 #LOCAL_DNS=`nslookup server | grep Server | cut -d ":" -f 2 | sed -e 's/^[ \t]*//'`
-LOCAL_DNS=(`cat /run/systemd/resolve/resolv.conf | grep ^nameserver | awk '{print $2}'`)
+LOCAL_DNS=(`grep ^nameserver /run/systemd/resolve/resolv.conf | awk '{print $2}'`)
 
 
 function merge_all_dns {
@@ -62,10 +62,7 @@ color_printf() {
 	local pad=$1
 	local str="$2"
 	# colored string length correction for printf formatting
-	#local wcolors=`wc -c <<< "$str"`
-	#local nocolors=`sed 's/\x1b\[[0-9;]*m//g' <<< "$str" | wc -c`
-	#local len=$(( $pad + wcolors - nocolors ))
-	local wocolors=`sed 's/\x1b\[[0-9;]*m//g' <<< "$str"`
+	local wocolors=`echo "$str" | sed 's/\x1b\[[0-9;]*m//g'`
 	local len=$(( $pad + ${#str} - ${#wocolors} ))
 	printf "%-${len}b" "$str"
 }
@@ -99,7 +96,7 @@ function Ping {
 		RESULT=$?
 		if [[ $RESULT -eq 0 ]]; then
 			local totaltime=`echo "$response" | awk -F '/' 'END {print $5}'`
-			totaltime=`bc <<< "scale=0;($totaltime+0.99)/1"`
+			totaltime=`echo "scale=0;($totaltime+0.99)/1" | bc`
 			total=`TimeColor $totaltime`
 			[[ $i -eq 0 ]] && echo -en "$OK\t$total\t" || echo -en "$total\t"
 			[[ $totaltime -ge $((GOODTIME*2)) ]] && break
@@ -143,9 +140,9 @@ function Curl {
 				-X POST -d '{"method":"stats", "params": {"rig_id":"-1", "passwd": "1"}}' \
 				${host}/worker/api`
 		fi
-		if [[ $? -eq 0 ]] && [[ $checkApi != "api" || ! -z $(jq -c "if .error.code then . else empty end" 2>/dev/null <<< "$response") ]]; then
+		if [[ $? -eq 0 ]] && [[ $checkApi != "api" || ! -z $(echo "$response" | jq -c "if .error.code then . else empty end" 2>/dev/null) ]]; then
 			local totaltime=`echo "$response" | tail -1`
-			totaltime=`bc <<< "scale=0;$totaltime*1000/1"`
+			totaltime=`echo "scale=0;$totaltime*1000/1" | bc`
 			total=`TimeColor $totaltime`
 			[[ $i -eq 0 ]] && echo -en "$OK\t$total\t" || echo -en "$total\t"
 			[[ $totaltime -ge $((GOODTIME*2)) ]] && break
@@ -202,17 +199,10 @@ function Connection {
 	local api_host=$3
 	local RESULT=0
 
-	NSLookup "$host" "$api_host"
-	[[ $? -ne 0 ]] && return 4
-
-	Ping "$host"
-	[[ $? -ne 0 ]] && ((RESULT++))
-
-	Curl "http://$host" $checkApi
-	[[ $? -ne 0 ]] && ((RESULT++))
-
-	Curl "https://$host" $checkApi
-	[[ $? -ne 0 ]] && ((RESULT++))
+	NSLookup "$host" "$api_host" || return 4
+	Ping "$host" || ((RESULT++))
+	Curl "http://$host" $checkApi || ((RESULT++))
+	Curl "https://$host" $checkApi || ((RESULT++))
 
 	return $RESULT
 }
@@ -232,7 +222,7 @@ function Connections {
 	done
 
 	#[[ ! -z $HIVE_HOST_URL ]] && API_HOST=`echo $HIVE_HOST_URL | awk -F'://' '{print $2}'` || API_HOST=
-	API_HOST=`grep -oP "://\K[^:^/]+" <<< "$HIVE_HOST_URL"`
+	API_HOST=`echo "$HIVE_HOST_URL" | grep -oP "://\K[^:^/]+"`
 	[[ -z $API_HOST ]] && echo -e $ERROR_COLOR"No API server defined in rig.conf"$NOCOLOR && exit 1
 
 	if [[ "$API_HOST" =~ hiveos.farm$ ]]; then
@@ -252,7 +242,7 @@ function Connections {
 			exitcode=$?
 			# return exicode only for current API server
 			[[ $host == $API_HOST ]] && RESULT=$exitcode
-			if [[ "${API_URLS[@]}" =~ /$host ]]; then
+			if [[ $exitcode -lt 4 && "${API_URLS[@]}" =~ /$host ]]; then
 				for url in "${API_URLS[@]}"
 				do
 					[[ ! $url =~ /$host ]] && continue
