LINUX NEW selfupgrade * add repository option * add --help context

diff --git a/hive/bin/selfupgrade b/hive/bin/selfupgrade
--- a/hive/bin/selfupgrade
+++ b/hive/bin/selfupgrade
@@ -8,6 +8,17 @@ export DEBIAN_FRONTEND=noninteractive
 #If needed maybe there is even stronger option @see https://askubuntu.com/questions/146921/how-do-i-apt-get-y-dist-upgrade-without-a-grub-config-prompt
 #sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
 
+help_context="USAGE
+\tselfupgrade [--force] [repository URL] [version]
+DESCRIPTION
+\tTool for upgrading HiveOS from repository.
+OPTIONS
+\t-f, --force\t\tforce upgrade; it can help in situations when selfupgrade says Hive is up to date but actually it isn't
+\trepository URL\t\tset repository to get updates from; should start with http like http://download.hiveos.farm/repo/binary or http://127.0.0.1/repo/binary
+\tverson\t\t\tspecify version to upgrade or downgrade; should use the following format x.y-zz, like 0.6-65
+EXAMPLE
+\tselfupgrade 0.6-65 http://192.168.0.1/repo/binary -f
+\t\t\t\tforce upgrade/downgrade to version 0.6-65 from repository http://192.168.0.1/repo/binary"
 
 
 current_version=`dpkg -s hive | grep '^Version: ' | sed 's/Version: //'`
@@ -20,25 +31,45 @@ screen -wipe > /dev/null 2>&1
 as=$(screen -ls | grep -c autoswitch)
 
 VERSION=
+existing_repository_list=
+repository_list=
 
-case $1 in
-	--force|-f) # it can help in situations when selfupgrade says Hive is up to date but this is not true
-		echo -e "${YELLOW}> Cleaning Hive apt lists${NOCOLOR}"
-		# force HiveOS lists download
-		rm -f /var/lib/apt/lists/*hiveos*
-	;;
+for param in $@; do
+	case $param in
+		--help)
+			echo -e "$help_context"
+			exit 0
+		;;
+		--force|-f) # it can help in situations when selfupgrade says Hive is up to date but this is not true
+			echo -e "${YELLOW}> Cleaning Hive apt lists${NOCOLOR}"
+			# force HiveOS lists download
+			rm -f /var/lib/apt/lists/*hiveos*
+		;;
 
-	*) # version
-		VERSION=$1
-		if [[ ! -z $VERSION ]]; then
-			[[ ! $VERSION =~ ^[0-9]+\.[0-9]+-[0-9]+$ ]] &&
-				echo -e "${YELLOW}Invalid version format \"$VERSION\"${NOCOLOR}" &&
-				echo -e "Please use the following format x.y-zz, like 0.5-12" &&
-				exit 1
-			echo -e "${YELLOW}> Upgrading to version ${WHITE}$VERSION${NOCOLOR}"
-		fi
-	;;
-esac
+		http*) #Set user repository
+			HIVEREPO_LIST=/etc/apt/sources.list.d/hiverepo.list
+			repository_list="deb $param /"
+
+			[[ -e $HIVEREPO_LIST ]] && existing_repository_list=$(cat $HIVEREPO_LIST)
+		;;
+
+		*) # version
+			VERSION=$param
+			if [[ ! -z $VERSION ]]; then
+				[[ ! $VERSION =~ ^[0-9]+\.[0-9]+-[0-9]+$ ]] &&
+					echo -e "${YELLOW}Invalid version format \"$VERSION\"${NOCOLOR}" &&
+					echo -e "Please use the following format x.y-zz, like 0.6-65" &&
+					exit 1
+				echo -e "${YELLOW}> Upgrading to version ${WHITE}$VERSION${NOCOLOR}"
+			fi
+		;;
+	esac
+done
+
+if [[ ! -z $repository_list && $existing_repository_list != $repository_list ]]; then
+	echo "Saving repository URLs"
+	echo "$repository_list" > $HIVEREPO_LIST
+fi
 
 #remove stupid rep file for smaller updates
 [[ -f /etc/apt/sources.list.d/amdgpu-pro.list ]] && rm /etc/apt/sources.list.d/amdgpu-pro.list
@@ -47,60 +78,68 @@ esac
 #Sometimes Ubuntu fails to update repos
 dpkg --configure -a
 
-hpkg update || exit $?
+hpkg update
+exitcode=$?
 
-
-if [[ -z $VERSION ]]; then #no target version
-	updateavail=`apt list --upgradable 2>&1 | grep '^hive' | wc -l`
-	if [[ $updateavail == 0 ]]; then
-		[[ -e /hive-config/RepoVer ]] && oldrepover=`cat /hive-config/RepoVer` || oldrepover=0
-		repover-touch
-		[[ -e /hive-config/RepoVer ]] && repover=`cat /hive-config/RepoVer` || repover=0
-		if [[ $repover != $oldrepover ]]; then
-			hello
-			echo -e "${GREEN}Upgrade to ${YELLOW}$current_version@$repover${GREEN} complete. Have a happy mining.${NOCOLOR}"
-		else
-			echo -e "${GREEN}Hive is up to date already${NOCOLOR}"
+if [[ $exitcode -eq 0 ]]; then
+	if [[ -z $VERSION ]]; then #no target version
+		updateavail=`apt list --upgradable 2>&1 | grep '^hive' | wc -l`
+		if [[ $updateavail == 0 ]]; then
+			[[ -e /hive-config/RepoVer ]] && oldrepover=`cat /hive-config/RepoVer` || oldrepover=0
+			repover-touch
+			[[ -e /hive-config/RepoVer ]] && repover=`cat /hive-config/RepoVer` || repover=0
+			if [[ $repover != $oldrepover ]]; then
+				hello
+				echo -e "${GREEN}Upgrade to ${YELLOW}$current_version@$repover${GREEN} complete. Have a happy mining.${NOCOLOR}"
+			else
+				echo -e "${GREEN}Hive is up to date already${NOCOLOR}"
+			fi
+			exit 0
 		fi
-		exit 0
+	fi
+
+	echo ------------------------------------------------------
+
+	if [[ -z $VERSION ]]; then #normal upgrade to the latest available
+		exitcode=0
+
+		hive_extra_packages=""
+		#check if hive-lib-dotnet is installed and if yes then add to checked packages
+		dpkg -s hive-lib-dotnet > /dev/null 2>&1 &&
+			hive_extra_packages="hive-lib-dotnet $hive_extra_packages"
+
+		#Here should be listed all non-miner packages so that versions check will work
+		apt-get install -y --only-upgrade hive hive-lib hive-opt $hive_extra_packages
+		aexitcode=$?
+		[[ $aexitcode -gt $exitcode ]] && exitcode=$aexitcode
+
+		#Update root miners packages, maybe some versions will be uninstalled
+		packages=$(hpkg getlist miners | grep -v '[0-9]')
+		if [[ ! -z $packages ]]; then
+			echo -e "${YELLOW}> Checking miners packages${NOCOLOR}"
+			apt-get install -y --only-upgrade $packages
+			aexitcode=$?
+			[[ $aexitcode -gt $exitcode ]] && exitcode=$aexitcode
+		fi
+
+		#Update version miners packages
+		packages=$(hpkg getlist miners | grep '[0-9]')
+		if [[ ! -z $packages ]]; then
+			echo -e "${YELLOW}> Checking miners version packages${NOCOLOR}"
+			apt-get install -y --only-upgrade $packages
+			aexitcode=$?
+			[[ $aexitcode -gt $exitcode ]] && exitcode=$aexitcode
+		fi
+	else
+		apt-get install -y --only-upgrade --allow-downgrades --reinstall hive=$VERSION
+		exitcode=$?
 	fi
 fi
 
-echo ------------------------------------------------------
-
-if [[ -z $VERSION ]]; then #normal upgrade to the latest available
-	exitcode=0
-
-	hive_extra_packages=""
-	#check if hive-lib-dotnet is installed and if yes then add to checked packages
-	dpkg -s hive-lib-dotnet > /dev/null 2>&1 &&
-		hive_extra_packages="hive-lib-dotnet $hive_extra_packages"
-
-	#Here should be listed all non-miner packages so that versions check will work
-	apt-get install -y --only-upgrade hive hive-lib hive-opt $hive_extra_packages
-	aexitcode=$?
-	[[ $aexitcode -gt $exitcode ]] && exitcode=$aexitcode
-
-	#Update root miners packages, maybe some versions will be uninstalled
-	packages=$(hpkg getlist miners | grep -v '[0-9]')
-	if [[ ! -z $packages ]]; then
-		echo -e "${YELLOW}> Checking miners packages${NOCOLOR}"
-		apt-get install -y --only-upgrade $packages
-		aexitcode=$?
-		[[ $aexitcode -gt $exitcode ]] && exitcode=$aexitcode
-	fi
-
-	#Update version miners packages
-	packages=$(hpkg getlist miners | grep '[0-9]')
-	if [[ ! -z $packages ]]; then
-		echo -e "${YELLOW}> Checking miners version packages${NOCOLOR}"
-		apt-get install -y --only-upgrade $packages
-		aexitcode=$?
-		[[ $aexitcode -gt $exitcode ]] && exitcode=$aexitcode
-	fi
-else
-	apt-get install -y --only-upgrade --allow-downgrades --reinstall hive=$VERSION
-	exitcode=$?
+#Restore old repository
+if [[ ! -z $existing_repository_list && $existing_repository_list != `cat $HIVEREPO_LIST` ]]; then
+	echo "Restoring old repository URLs"
+	echo "$existing_repository_list" > $HIVEREPO_LIST
 fi
 
 [[ $exitcode -ne 0 ]] && echo -e "${RED}Upgrade failed${NOCOLOR}" && exit $exitcode
@@ -152,7 +191,6 @@ current_version=`dpkg -s hive | grep '^Version: ' | sed 's/Version: //'`
 	repover=`cat /hive-config/RepoVer` ||
 	repover=0
 echo -e "${GREEN}Upgrade to ${YELLOW}$current_version@$repover${GREEN} complete. Have a happy mining.${NOCOLOR}"
-
 
 #Flush buffers if any files changed
 sync
