selfupgrade VERSION

diff --git a/hive/bin/selfupgrade b/hive/bin/selfupgrade
--- a/hive/bin/selfupgrade
+++ b/hive/bin/selfupgrade
@@ -2,6 +2,16 @@
 
 . colors
 
+VERSION=$1
+
+if [[ ! -z $VERSION ]]; then
+	[[ ! $VERSION =~ ^[0-9]+\.[0-9]+-[0-9]+$ ]] &&
+		echo -e "${YELLOW}Invalid version format \"$VERSION\"${NOCOLOR}" &&
+		echo -e "Please use the following format x.y-zz, like 0.5-12" &&
+		exit 1
+fi
+
+
 #remove stupid rep file for smaller updates
 [[ -f /etc/apt/sources.list.d/amdgpu-pro.list ]] && rm /etc/apt/sources.list.d/amdgpu-pro.list
 
@@ -17,14 +27,22 @@ exitcode=$?
 [[ $exitcode -ne 0 ]] && echo -e "${RED}Repository update failed${NOCOLOR}" && exit $exitcode
 
 
-updateavail=`apt list --upgradable 2>&1 | grep hive | wc -l`
-[[ $updateavail == 0 ]] &&
-	echo -e "${GREEN}Hive is up to date already${NOCOLOR}" &&
-	exit 0
+if [[ -z $VERSION ]]; then #no target version
+	updateavail=`apt list --upgradable 2>&1 | grep hive | wc -l`
+	if [[ $updateavail == 0 ]]; then
+		echo -e "${GREEN}Hive is up to date already${NOCOLOR}"
+		exit 0
+	fi
+fi
 
 echo ------------------------------------------------------
 
-apt-get upgrade -y hive
+if [[ -z $VERSION ]]; then #normal upgrade to the latest available
+	apt-get upgrade -y hive
+else
+	apt-get install -y --allow-downgrades --reinstall hive=$VERSION
+fi
+
 exitcode=$?
 [[ $exitcode -ne 0 ]] && echo -e "${RED}Upgrade failed${NOCOLOR}" && exit $exitcode
 
